### ISSUE TITLE
Feature Request: Periodic Sanity Check for "Offline" channels

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#1029]
![image](https://user-images.githubusercontent.com/1767796/59165478-0fd62080-8ad1-11e9-9cec-cb479cb58559.png)
I have attached a screenshot showing a channel with a funding transaction ID that **_is not in the blockchain_**.  The TxID is 30eccbb2752cc1e57a01298e38c1f0c1e9f05ada5b15effef6836433ec5b53c2
My request is that at startup, Eclair collect the funding TxIDs for all of its OFFLINE channels and ask its connected full node to getrawtransaction that TxID.  If it errors out, let the user choose to keep the channel or remove it.  

It's easy enough to force-close the channel, but I wouldn't want to do that if the channel were real.  The feature request automates the work of establishing whether or not the funding transaction actually exists.

While it makes sense that this situation (a channel with a non-existent funding Tx) should never exist, I can see a few ways that it might happen - orphaned blocks, sybil attacks, and bugs.

I am (very slowly) learning scala, so I could work on this, and it will get done faster is someone points me in the right direction.  For example, PATH/FILE.scala has startup code such as FUNCTION, and you can find examples of making RPC calls in ...

Thanks!

**Comment by viaj3ro** [comment]
I had a couple of those zombie channels as well. It definitely some investigation effort to figure out whats going on. The best clue is the missing short channel ID. I'd say it would be OK, to just drop them if funded by peer.

**Comment by pm47** [comment]
What version of eclair are you running? This was fixed by #714, released on May 10th. The channel should be cleaned up 10 min after startup.

I was actually working on corner cases related to this yesterday as part of #1015, but I now think it is better to do it is a separate PR. The remaining issue is that if you force close the channel in this scenario, eclair won't be able to clean it up. The solution is indeed to verify that the funding tx is in the blockchain, but we need to be very careful (especially on mobile where electrum servers are less reliable than a local bitcoind) because we risk losing money in case of false negative.

**Comment by dscotese** [comment]
I believe 1034 is the fix that would have prevented my issue.  I was using v0.3, and the timestamp on the jar file is May 11th.
