### ISSUE TITLE
Memory Leak in cachedLightningMessageCodec

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#1031]
I am running Eclair on a server with 8gig of RAM so the max heap is defaulting to 2Gig.

After running for a week or so I am running out of heap. The OldGen is hitting 100% and the GC can not clear it down.

Looking at a heap dump after running for a few days (I just enabled heap dump on OOM - so will update issue next time there is a crash) I see that 288meg is LightningMessageCodecs and the Guava LocalCache in it - and about 60k entries. Is this expected?
As additionally I see the 34k ChannelAnnouncement and 60k ChannelUpdate elsewhere.

But now after a restart and the server only running for 24hours there are only 6.5k entries in the cache and it is only using 30Meg? Although in this restarted instance I have 200Meg in the Router in state data?

I assume the weakkeys setting on the cache is confusing something.

Will update next time I get an OOM.

**Comment by n1bor** [comment]
I think I understand it now. When eclair starts up it loads the 34k Announcements and 60k updates from the networkdb. However since these are decoded from the binary format as they are loaded they do not get added to the cache. (Cache is a cache of Class->binary).
But then over time as we send messages these get added to the cache.

This does raise the question if after 24 hours there were only 6.5k entries in the cache is it sensible to have it unbound in size? As add 30%+ to the memory usage of the service.
If it was bound to say 1000 entries think that would cover the common case of sending the same update to 200 peers.

**Comment by n1bor** [comment]
Also makes it hard to manage a process that is expected to grow Heap Usage by 30% over a 1 week period - and hard to know if there really is a memory leak.

**Comment by pm47** [comment]
I've run into this as part of our work on monitoring (which is almost ready™ and should be pushed soon™).

The idea with the `.weakKeys()` setting is that instead of assigning a max size for the cache, we tell guava to use all the available heap and it is up to the GC to clean up space if needed. It turns out that performance gains are not that great, they come at a cost of significant pressure on the GC (and, of course, heap usage, but that was the point).

When removed, the heap usage becomes very stable, which I think is much better than hypothetical performance gains. I'll submit a PR.

**Comment by n1bor** [comment]
I think cos the keys for all valid updates etc.. are kept in the Router they never get gc'd so neither does the key or value in the cache - hence grows to 60k++. But agree can not see how serialising a small class can take that long - lot less than the channel class!

**Comment by n1bor** [comment]
Thanks - upgraded day or so ago and looking better:
https://lightningconductor.net/grafana/d/L7z_sOkWk/eclair-jvm-stats?orgId=1&from=1558030518255&to=1560622518257
