### ISSUE TITLE
Storing payments in a db

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#121]
A service I'm working on needs to be able to query Eclair if certain payment request has been fulfilled or not (some basic related work can be seen here: https://github.com/btcontract/eclair/commit/42fb4dd2b7a9fde6c1a12498eccd53fe9dc4c19a), eventually this will have to be stored in a db for better reliability.

I could go on and add a database of my choice but before doing that I'd like to ask if there are any plans to use some particular kind of database? If there are I'd use it for consistency sake.

**Comment by pm47** [comment]
Hi Anton,

Sorry I never got back to you about #84. Yes we plan to replace our current plain files to something akin to sqlite (still undecided), but that would be for storing protocol-level stuff (e.g. network announcements). 

But the kind of things you are talking about is more high level, and I am not even sure it belongs to eclair. Everything you need is already in place to extend the library though. What you want to do is choosing `NoopPaymentHandler` instead of `LocalPaymentHandler` when starting eclair, which allows you to customize how payments are generated and managed, etc.

How does that sound?

**Comment by btcontract** [comment]
It sounds good. Just to make sure we're on a same page: I'll have to create a custom PaymentHandler which manages payments via db and then I'll be querying a db instead of Eclair?

**Comment by pm47** [comment]
Yes, that would allow you to use the vanilla eclair-core lib and extend it the way you like.
