### ISSUE TITLE
Channel from Android wallet goest to CLOSED status immediately.

### ISSUE THREAD

**Issue by deafboy** [ACINQ/eclair#122]
Channel opened from Android wallet to desktop eclair goes to closed status shortly after creation attempt.

[eclair.log.txt](https://github.com/ACINQ/eclair/files/1188613/eclair.log.txt)

**Comment by pm47** [comment]
The reason is given in the log file:

> local/remote feerates are too different: remoteFeeratePerKw=11110 localFeeratePerKw=1108

This happens when parties can't agree on an acceptable network fee and is "a feature not a bug". The problem is that with current bitcoin core version, fee estimates can vary a lot between two nodes. Let's wait for bitcoin core 0.15, there have been some improvements in this area.

In the meantime, add this to your eclair.conf: 
```
eclair.max-feerate-mismatch=100000
```

This essentially disables the check.

**Comment by btcontract** [comment]
What if statistical methods could be used here? A fee history could be stored and on each new feerate we could add it to the list, then filter out rates beyond 1st standard deviation, then take a mean of the rest as current fee.

Thus, gradual changes in rates will be preserved and inadequate outliers will be filtered out. 
I can try to implement this if it sounds like a good idea.

**Comment by pm47** [comment]
I'd like to keep anything fee-related as much outside of eclair as possible, as it is in theory a completely separate issue. I think we need to have more real-world feedback before going further.

As for the issue at hand I think it can be closed @deafboy?
