### ISSUE TITLE
Funder should refresh the `update_fee` on reconnection

### ISSUE THREAD

**Issue by pm47** [ACINQ/eclair#1381]
Funder is responsible for keeping the channel feerate in sync with the bitcoin network by sending `update_fee` from time to time. Our current policy is to do this when channels receive the `CurrentFeerates` event, which is sent every 10 minutes.

This works well for always-connected peers, but not for mostly-offline peers like mobile nodes. On reconnection, funder should check if the channel feerate is off (with `Helpers.shouldUpdateFee`) and send an `update_fee` if needed.

**Comment by t-bast** [comment]
Our current architecture doesn't allow us to do this very easily.
I see at least three very different ways of handling that:

1. In the channel actor, when handling a feerate change while offline, stash the message if we should send an `update_fee`. When coming online, unstash messages. The issue is that there are likely many such messages that will end up being stashed, and that will trigger an unnecessary flood of `update_fee` on reconnect.
2. In the channel actor, when handling a feerate change while offline, store it in the state. When coming online, look at the state to get the latest feerate and send `update_fee` if needed. I'm not a big fan of updating the state classes for that though.
3. Move the recurring task of fetching fees every 10 minutes inside a dedicated actor (instead of a timer task launched in `Setup`. When a channel comes online, it can then ask this actor to get the fees (via either a direct message, or an event).

I'm leaning more towards option 3, it will also allow us more flexibility with how we handle fee updates in the future. Let me know what you think before I dive into the implementation.

**Comment by araspitzu** [comment]
I have a different take: i think we should "turn around" the feerate notification mechanism. Currently we  compute new fees (and optionally update them and send `update_fee`) only when we receive a `CurrentFeeRate` event, this happens every 10 minutes. I propose to _look_ into the current feerate everytime we receive a `channel_reestablish` and apply the old logic: if fees are different we send out an `update_fee`.

_Looking_ into the feerate at any given time requires some changes, probably storing the last `CurrentFeeRate` somewhere accessible via `NodeParams`.

**Comment by t-bast** [comment]
> I propose to look into the current feerate everytime we receive a channel_reestablish

This is not sufficient though, we also need to keep doing this at every block, right?

> Looking into the feerate at any given time requires some changes

I agree, that's why I proposed solution 3: a dedicated actor that broadcasts the fees every 10 minutes, but can also provide them on-demand (you send a message to this actor and it answers with the fees).

**Comment by t-bast** [comment]
I dived a bit more into our feerate handling and I understand better what you're saying. The issue is that we have a very weird model with the `feeEstimator` that provides "direct" access to the fees and requires some mutable `AtomicRefs` (which goes against the actor model)...but if we're ok with having those as mutable variables directly accessible in `nodeParams`, why not put the current feerate directly in there and leverage that (instead of the `feeEstimator` that provides only a subset of what we want)?

**Comment by t-bast** [comment]
Actually in the short term, we can in fact leverage the `nodeParams.feeEstimator`, because it has the latest feerate!

**Comment by pm47** [comment]
>> I propose to look into the current feerate everytime we receive a channel_reestablish

>This is not sufficient though, we also need to keep doing this at every block, right?

That is what I had in mind when I opened the ticket. We could just send a `CurrentFeerate` to ourselves after each connection reestablish to avoid duplication of logic, and to minimize the impact of us looking directly in `nodeParams`.
