### ISSUE TITLE
Incorrect amount displayed in UI

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#139]
Here's an actual channel amount:
```scala
val canReceiveAmount = d.commitments.localCommit.spec.toRemoteMsat
val canSendAmount = d.commitments.localCommit.spec.toLocalMsat
println(s"canReceiveAmount: $canReceiveAmount, canSendAmount: $canSendAmount")
// output: canReceiveAmount: 5611755950, canSendAmount: 4388244050
```  
Last 50 msat are lost in UI:
![screenshot from 2017-08-25 10-37-47](https://user-images.githubusercontent.com/9870980/29704325-01c7d6a2-8982-11e7-8758-903433bb5876.png)

This happens because UI uses `millisatoshi2millibtc` method which converts msat to sat and thus -milli part is always lost.

**Comment by dpad85** [comment]
Indeed this an effect of the conversion to `mBTC`. **For the UI**, the `msat` part is not important and even confuse the user. It is not a problem that this value is truncated when the amount is displayed.

However, the formatting here is not consistent and we need to improve that. What do you think of formatting `mBTC` amounts with 5 decimals?

I propose these patterns for `BTC ` and `mBTC`
```scala
val BTC_PATTERN = "###,##0.000#####"
val MILLI_BTC_PATTERN = "###,##0.00000"
```

So in your case, `4388244050 msat` would print as `43,88244 mBTC`, `5611755950 msat` would print as `5611755 mBTC`.

**Comment by btcontract** [comment]
Ugh well, I've made a decision to show amounts in Satoshi (and fiat) only so `4388244050` is displayed as `43,882,440.5` in my wallet. Like what if msat will become relevant shortly after all this takes off? (wishful thinking, I know).

I might reconsider and switch to mBTC if you think using Satoshi is a terribly bad idea. 
But I like Satoshi because it's natural so to say.

**Comment by btcontract** [comment]
Also, my reasoning was that if users are allowed to enter amounts like "1000.5" Satoshi (possible in Eclair currently) they should also be allowed to see them.

**Comment by dpad85** [comment]
Yes a user can send a fraction of satoshis with Eclair and it would make sense to display the exact balance. However once the channel is closed the balance is truncated to satoshis, because msat does not exist in bitcoin (yet), so it's not really useful and some users may find this confusing since your theoretical balance would not exactly match the final balance.

By the way I prefer to denominate amounts in mBTC since it's currently the closest to 1$ ou 1€ and as such it gives a immediate perception of the fiat value of a payment. 😄

The next step is an option that enable the user to choose the unit he prefers.
