### ISSUE TITLE
channelstats API call only returns data for locally opened channels

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1449]
The data for remotely opened channels is missing.

**Comment by t-bast** [comment]
`channelstats` returns data for all your channels, whether you opened them or a node opened them to you. It does *not* return data for channels that aren't yours obviously, since there's no way you'll have this information.

If data doesn't appear for one of your channels, it simply means that no payment was relayed/made through that channel.

If that isn't the behavior you observe, please re-open with logs showcasing the issue.

**Comment by viaj3ro** [comment]
no, it only returns data for channels I opened myself but not for channels peers opened to me. Not sure how logs are any help in this case.

Just run `channelstats` and try finding any information for a channel you haven't opened yourself. At least for me and some others running 0.4 or earlier it doesn't return any data for those.

**Comment by t-bast** [comment]
Oh my, you're right, there is a bug there! For some weird reason we link channel stats to on-chain fees paid, so we only show you stats for channels for which you paid on-chain fees.

That's definitely not intended :confused: so let me investigate and fix this, thanks for insisting!
