### ISSUE TITLE
On-chain send funds API

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ACINQ/eclair#1458]
In order to offer better on-chain insights and features to the user, we request to add on-chain send funds API.

Request Params:
bitcoin address - mandatory
amount - mandatory
confirmation blocks - mandatory if fee rate is missing
fee rate - mandatory if confirmation blocks is missing

Response:
transaction id/error details

Sample UI design:
![image](https://user-images.githubusercontent.com/23240721/84654433-2cbfe380-aedd-11ea-9bb4-4f9a2f5b1700.png)

**Comment by t-bast** [comment]
`bitcoind`'s [sendtoaddress](https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/sendtoaddress/) supports setting the confirmation blocks, but not the mode where you set the feerate.

I really don't want eclair to implement the wallet logic of creating a raw transaction based on user's feerate, is it ok if we only implement the "confirmation blocks" option? Otherwise I can do a reverse lookup and transform an incoming "feerate" into a "confirmation blocks" I would give to `bitcoind`, but that means I wouldn't be honoring exactly the user's requested feerate, so I don't know if that would be ok.

**Comment by saubyk** [comment]
Hi @t-bast , the above suggestion for fee-rate/target blocks option is based on the features available on both LND and C-Lightning implementations.
You can decide to offer just one, if you feel that keeps Eclair implementation simple. I am wondering if similar logic is applied in Eclair for channel opening with the `fundingFeerateSateByte` option.

I can tell you from experience and especially for opening channels the feature of specifying sats/byte is pretty popular. As people like the flexibility of specifying low rates and 1 sat/byte is an especially popular rate. :-)

**Comment by t-bast** [comment]
> I am wondering if similar logic is applied in Eclair for channel opening with the fundingFeerateSateByte option

This is because we're building the raw funding transaction ourselves that we're able to choose the exact feerate, but I don't want to support that for arbitrary send transactions (implementing a good enough Bitcoin wallet is a full project in itself, I want eclair to do one thing and do it right and focus on the lightning side of things :slightly_smiling_face:).

We'll start with support for `confirmation_blocks` only for now, and we'll see if we revisit that later!

**Comment by saubyk** [comment]
Hi @t-bast understood. Thanks.
