### ISSUE TITLE
Update relay fee API throws error with multiple channels

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ACINQ/eclair#1467]
The API [updaterelayfee](https://acinq.github.io/eclair/#updaterelayfee) suggests that, "The endpoint supports receiving multiple channel id(s) or short channel id(s), to update multiple channel you can use the parameters channelIds or shortChannelIds". 

But, we are getting below error while sending multiple channelIds.

Error:
The form field 'channelId/shortChannelId' was malformed:Must specify either the channelId or shortChannelId

Sample request data:
{
	"feeBaseMsat": "1000",
	"feeProportionalMillionths": "200",
	"channelIds": "b9301e9f7...924cd,bf356...c199"
}

**Comment by t-bast** [comment]
That's because we updated the API documentation a bit too soon. What you're trying will work on master, but not on the latest release.

I'm adding some more APIs for you guys, once all the pieces are there we'll release a new version of eclair and fully update the documentation.
________________________________
