### ISSUE TITLE
Missing fee information in the findroutetonode API

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ACINQ/eclair#1471]
Current API `'findroutetonode` to query the route only returns the nodeId from hops. 

It will be very useful to the user, if we can at least show every hop's capacity and estimated fee per hop.

**Comment by t-bast** [comment]
While I understand why you're asking for it, I think it's less useful than you think.

The fee results this would return would likely not be indicative of the fees you would be paying when you actually make the payment, for many reasons:

- it's only valid at a given point in time, based on the info we have: when attempting the payment, any node in the route could send us an updated channel_update asking for more fees, invalidating the result you showed the user
- the payment state machine will retry in case a route fails, and the fees paid (and route used) will likely be quite different from the result of `findroutetonode`. As long as the fee does match the user's max-fee (configured in his `eclair.conf`), we will make the payment
- the reason for the previous point is that it's very rare for a payment to work with the first route found, unless it's to a neighbour node. If we had to pause between each attempt to ask the user if he agreed to the updated fee, the UX would be horrible because that would happen a lot

This is the reason why we currently do not show this information in `findroutetonode`, because it's likely that if we do we'll have tons of user tickets saying "findroutetonode told me I'd pay X fees but in the end I paid Y fees, why is that?".

If after all these gotchas you still think this is useful, I can add that when I have some buffer time, but right now on LN I think it's a better UX to just tell the user to set the maximum fee he thinks is reasonable for a payment and then let the path-finding state machine do its job (it cannot do an accurate "dry-run" without actually sending the HTLCs).

**Comment by ShahanaFarooqui** [comment]
@t-bast, After opening the issue yesterday, Suheb and I had almost the same discussion. Suheb also agrees that this fee cannot even be considered as estimate.  We already struggle with a lot of issues/questions related to these fee estimates with LND implementation. 

My only concern was that if the user cannot even get the estimate then why does even this API exist. But, as it is impossible to estimate the fee correctly then it is equally useless. Thanks for the explaination. Closing the issue now.

**Comment by t-bast** [comment]
> why does even this API exist

This is a good point :)

I think the API still has some value. It lets you see whether you have a path to a given node and how far that node is.
You can use that information to decide to open new channels to increase your connectivity.
It's an API for graph topology more than payment/fees.
