### ISSUE TITLE
[Feature Request] API for channel age, idle and offline days

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#1616]
To be able to determine the usefulness of channels and weather to keep them open it would be extremely helpful to have the API return info about channel age, idle and offline days. 
Some channels have routed a lot in the past but didn't rout any incoming or outcoming payments in months or years. Some are even offline since ages. 

With this info it would be much easier to optimize routing and apply liquidity efficiently which in turn would make the LN experience better for everyone.

**Comment by remyers** [comment]
Currently [`channelstats`](https://acinq.github.io/eclair/#channelstats) shows information that can help gauge the usefulness of channels: `paymentCount`, `relayFee` and `avgPaymentAmount`. The `--from` argument can be used to show the most recent time period; eg. to show the last month of channel stats:
```
eclair-cli channelstats --from=`date -d "- 1 month" +"%s"`
```
Additional information we could add to the `channelstats` results to provide what @viaj3ro is asking for would be:

- `lifetime` : the duration (iso, unix) this channel has been open, or the duration of the  `--from`  to `--to` period, whichever is less
- `downtime` : the duration (iso, unix) our peer for this channel has been offline/unavailable during the `--from` to `--to` period
- `idle` : the duration (iso, unix) that there has been no routing activity with this channel during the `--from` to `--to` period

@viaj3ro - what value does the `idle` value add over just looking at the `relayFee` or `downtime` of a channel for a given period?

I propose reporting both a human readable duration (iso) and seconds (unix); the former for manual use and unix seconds for automated use.

Both `downtime` and `idle` should also not include periods of time when our node is not running.

To judge the quality of a channel we'd like to see the aggregate activity in both directions.  Right now `channelstats` gives separate results for each `direction` ("IN", "OUT'). Perhaps we could add a `direction` of "BOTH" to create a result record that combines the values from both of the "IN" and "OUT" records. 

Another option is to add an argument like `--aggregate` to create records with the "BOTH" direction only.

We could add a new API command `channeluptime` instead of modifying `channelstats` but I think it makes more sense to add these new time based statistics to `channelstats`.

**Comment by remyers** [comment]
@thomash-acinq do you have any comments on this feature for helping manage channels/liquidity?

**Comment by thomash-acinq** [comment]
There are many heuristics that one could use to manage channels. I personally don't think that these specific signals are important but anyway I don't think it is desirable to start adding API commands for this kind of thing. Eclair already puts all the relevant information in its database, I would advise to read directly from the database, it has all the data you want and you can use SQL, just be sure to not write anything in it from outside of eclair.

**Comment by remyers** [comment]
Thanks for the feedback. I don't think we currently log `downtime`, but I can see that it may not be important because reduced relay fees from a channel with high downtime capture this information better.

**Comment by viaj3ro** [comment]
what I meant by idle/offline days is a counter that just counts the days since the last routing activity or for offline channels, the days since the peer was last seen online. It would be very useful info because it would allow a GUI like RTL to show how long a channel wasn't in use or offline and would be a good closing candidate.

**Comment by remyers** [comment]
There seems to be two questions about this feature:

1. Should we add API commands for channel monitoring information that can be extracted from the databases directly?
2. Is it valuable for Eclair to log peers/channels offline and idle time in a database in addition to what is already reported by the `channelstats` ?

Perhaps instead of API commands, a guide on how to summarize this information directly from the database would be more valuable for node operators and allow them to more easily customize the metrics they use to manage their node.

I can not say how useful or not it is to record when peers/channels are offline and idle. Should a node operator be more or less likely to want to close a channel that is not routing significant value if it has been offline or idle?

**Comment by viaj3ro** [comment]
Yes, I'd argue a as a routing node operator it is desirable to close channels that have not have any routing activity since weeks or months. It is just wasted liquidity. Same goes for channels to zombie nodes that haven't been online in a long while.
Therefore it would be desirable to have access to this information in a quick and easy way. Right now it is quite difficult to get or not even possible at all.

What's the downside of giving easy access via API or otherwise?

**Comment by remyers** [comment]
> What's the downside of giving easy access via API or otherwise?

I believe the issue is more about trying to put every possible channel report in the API vs. node operators accessing this information from the database in whatever customized way they want.

Are there any SQL tools you would recommend @thomash-acinq for generating channel reports directly from Eclair's databases?

**Comment by viaj3ro** [comment]
The reason why I opened the issue was that I was talking with @ShahanaFarooqui how to best offer such (still super basic) channel monitoring functionality in RTL. Back then her reply basically was, they would need an API call that returns such data, then it would be easy to implement. Without that, I believe she saw no feasible way.

**Comment by remyers** [comment]
The right solution is really a dedicated tool with access to a read-only copy of Eclair's databases that can give a node operator suggestions based on best practices. 

Unfortunately we're still learning what metrics and heuristics are important so it's premature to build such a tool. Until then, I think experimenting with making read-only SQL queries to your node database to monitor your channels is the best approach.

**Comment by viaj3ro** [comment]
this sounds a bit like the perfect is the enemy of the good situation. 

Instead of a good solution now, we will have a perfect solution in years or maybe never.

**Comment by t-bast** [comment]
It's a matter of available dev time and technical debt. We can't commit the time to add this to eclair-core and maintain it potentially forever, as we believe it's a short-term fix for something that should be done very differently.

However, this should be very much doable by a 3rd-party eclair plugin, which would be my preferred solution. If other eclair node operators feel this is useful, you could convince one of them to write such a plugin?

**Comment by viaj3ro** [comment]
ok. I will try and find one who is able and willing to create such a plugin. In case you know of any potential candidates, let me know.

**Comment by t-bast** [comment]
I think the most likely candidates would be on the eclair node operators Telegram group (t.me/eclair_lightning)
