### ISSUE TITLE
Channel.scala: multiarg infix syntax looks like a tuple and will be deprecated

### ISSUE THREAD

**Issue by ysangkok** [ACINQ/eclair#1627]
I noticed this warning and didn't see an issue about it:

```
[WARNING] eclair-master/eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala:661: warning: multiarg infix syntax looks like a tuple and will be deprecated
[ERROR]           handleCommandError(cause, c) acking(d.channelId, c)
```

**Comment by pm47** [comment]
The issue is https://github.com/ACINQ/eclair/issues/1393.

Since moving to scala 2.12 / akka 2.6 on master, we had to disable strict compiler warnings, because we need to keep compatibility with the android branch which remaing on older versions. We'll be moving to a new architecture for mobile apps soon, which will allow us to drop backward compatibility and go back to strict compiler settings.

**Comment by ysangkok** [comment]
Oh, sorry for the duplicate, I will close this then.
