### ISSUE TITLE
channelReserve unit unclear from documentation

### ISSUE THREAD

**Issue by Kixunil** [ACINQ/eclair#1739]
Expected: API doc clearly states whether `channelReserve` is sat or msat.

Current state: API doc has no such informtion. Quick look at the code suggests that it's most likely in sats. This seems to make sense looking at the data.

Steps to reproduce:

1. open https://acinq.github.io/eclair/#channels-2
2. look at channel reserve

Version and environment: Irrelevant, I believe

**Comment by pm47** [comment]
Good catch, that is also true for `dustLimit` and maybe other values.

Do you feel like trying to fix that?

**Comment by t-bast** [comment]
Right, it's a bit of a pain to know whether something is in `sat` or `msat` sometimes, it should be documented.
If you have time to look at it, you should open a PR against the `slate-doc` branch as described [here](https://github.com/ACINQ/eclair/blob/master/BUILD.md#build-the-api-documentation).
It means changing a bit of markdown, and we will deploy the updated site afterwards.

**Comment by Kixunil** [comment]
Hmm, never worked with slate and I'm not sure from the example how to annotate *responses*. Can you give me a hint?

**Comment by t-bast** [comment]
You don't need to work with slate, just modify the markdown in `index.html.md` in the `slate-doc` branch and open a PR with your changes, and I'll run the slate scripts to build the HTML site and deploy.

You can just add a sentence explaining that specific fields are in satoshi in the section for that request/response (since JSON doesn't support inline comments).

**Comment by t-bast** [comment]
The website has been updated with the latest documentation.
Thanks for your contribution!
