### ISSUE TITLE
GetSentInfo yields different behavior using id and payment hash from the same payment.

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#1843]
Using the "Bash Launcher" console window to run Eclair-cli on Windows 10: Providing the paymentId as reported by SendToRoute yields an empty array, but providing the paymentHash used in the SendToRoute command yields a payment with the ID as reported by SendToRoute.

I expect the Payment ID provided by SendToRoute, used as `id` and the paymentHash provided to SendToRoute, used as `paymenthash` both to yield the same results from GetSentInfo.

I have only done this testing with one SendToRoute result.

I downloaded "version": "0.6.0-f89b092" from the Releases page.

Windows 10, openjdk version "11.0.10" 2021-01-19

**Comment by t-bast** [comment]
There are a few subtleties with `getsentinfo`:

- if you provide the `paymentId`, it will only return results for this `paymentId` (if there is any)
- if you provide the `paymentHash` it will return all payment attempts to pay this `paymentHash` (potentially multiple `paymentId`s)
- when you provide a `paymentId`, it must be the `parentPaymentId` (this is because of MPP, we have one parent `paymentId` that represents this payment attempt, and will itself create potentially multiple child payments with their own ids)

I suspect the discrepancy you're seeing is because of the last point: you likely provided a child `paymentId` instead of the parent. Can you test and confirm?

**Comment by dscotese** [comment]
That is absolutely right.  The documentation for GetSentInfo should explain this :-)

**Comment by t-bast** [comment]
Fixed in https://github.com/ACINQ/eclair/commit/27bb56d8548170312e54d1c141966bdf242094d6, the documentation website will be updated in our next release.
