### ISSUE TITLE
Update error message when testnet estimatesmartfee fails

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#1850]
I'm experiencing crash with

Logs
```
2021-06-26 16:32:26,737 WARN  fr.acinq.eclair.Setup - cannot retrieve feerates: estimatesmartfee failed: Insufficient data or no feerate found
```
Error message
```
fatal error: cannot retrieve feerates: channels may be at risk
```
Actual local mempool statistics

```
{
  "loaded": true,
  "size": 44,
  "bytes": 7473,
  "usage": 55808,
  "total_fee": 0.00321238,
  "maxmempool": 50000000,
  "mempoolminfee": 0.00000000,
  "minrelaytxfee": 0.00000000,
  "unbroadcastcount": 0
}
```
Eclair version `master` commit af618bc44fe6054957f65d77000a460c14b41f30.

Actually just recently the node was fine and worked. I do not know what exactly happened which might lead to such results.

**Comment by engenegr** [comment]
Hint by Anton that it is somehow related to bitcoind. I indeed have 
```
{
  "errors": [
    "Insufficient data or no feerate found"
  ],
  "blocks": 0
}
```
from my bitcoind instance after `bitcoin-cli -testnet estimatesmartfee 6`

**Comment by engenegr** [comment]
Sorry, it works now.

It seems Bitcoin Core collected enough transactions and now able to serve fees. It is up on you to close this issue. In my opinion node shouldn't crash with such error. 

BTW you have another issue with the similar error.

**Comment by t-bast** [comment]
We could change the error message (to hint that maybe you're on `testnet`/`regtest` and should just wait for a few test blocks), but apart from that I'm not sure what we should do differently? If we cannot retrieve feerates, the node is really at risk. Crashing the node is the best way to alert the operator and ensure they can fix this (by fixing their bitcoind node).

This happens on `regtest` and `testnet` because you usually don't run test nodes like mainnet ones, and `bitcoind` doesn't have enough data to estimate the fees. It never happens on `mainnet` (unless there is something really wrong with your node), so I'm not sure it's worth fixing. Do you have a suggestion of what you'd change?

**Comment by engenegr** [comment]
Well, yes. Maybe changing error message on kind-of-alert "wait and restart node" makes sense in this situation.

**Comment by t-bast** [comment]
Can you try submitting a PR to fix that?

**Comment by engenegr** [comment]
Sure, why not.
