### ISSUE TITLE
Mainnet node doesn't start without wallet name

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#1868]
I have two setups using bitcoind v21.99.0.

Eclair testnet (SQLite backend) has started without `wallet` parameter in config while mainnet (Postgre) didn't and I could only make it working with provided `wallet`.

I had to restart mainnet bitcoind because I was thinking that it was in failed state but apparently wallet was loaded and I reloaded it again after restart. Everything returned back to normal only after explicit definition `eclair.bitcoind.wallet`.

**Comment by t-bast** [comment]
What is bitcoind v21.99.0? Note that we may not support bitcoind versions outside of the ones we recommend (0.20.1 or 0.21.1).

> apparently wallet was loaded and I reloaded it again after restart. Everything returned back to normal only after explicit definition eclair.bitcoind.wallet.

I think this is your issue: you had a wallet loaded in `bitcoind` and eclair didn't know about it.
We want this configuration to be very explicit, because we don't want eclair to be using funds from the linked bitcoind that it's not supposed to use.

IMO this is expected behavior. You must verify the wallet you configure for eclair before starting up. What kind of different behavior would you expect? Maybe better error messages to guide you to configure the wallet? We have a section in our README for that (https://github.com/ACINQ/eclair#configure-bitcoin-core-wallet), it's only the term "default loaded bitcoin wallet" which may be misleading.

**Comment by engenegr** [comment]
> IMO this is expected behavior. You must verify the wallet you configure for eclair before starting up.

Fine. But I haven't configured it for testnet, started node, it said my wallet is not loaded into bitcoind, then I loaded it and restarted node. It was running without config on the testnet. This is why I didn't expect any disruption on Mainnet.

Only after Eclair declined to start without wallet (when in fact it was loaded) I discovered that there is new option now.

**Comment by t-bast** [comment]
I think the difference you saw between testnet and mainnet is because in one case you had a wallet loaded (different from the `""` default wallet).

I agree though that we could make this better, it's hard to understand what's wrong for users.
At startup, we could make a few calls to `bitcoind` to list wallets and check how it's configured, and return a more detailed error message to users if we think it's not properly configured. Feel free to try to implement that if you have time, otherwise we'll do it when we have some buffer.

**Comment by engenegr** [comment]
> I think the difference you saw between testnet and mainnet is because in one case you had a wallet loaded (different from the "" default wallet)

Yes. I agree, it looks like that.
On both machines I have bitcoind wallets with same names.

Sure I could try it. It demands a bit more involvement. But I suggest just config parameter check. If you make dedicated wallet a requirement, the corresponding entry also must be provided.
