### ISSUE TITLE
"Open transaction in explorer" should open the blockcypher web client

### ISSUE THREAD

**Issue by fresheneesz** [ACINQ/eclair#191]
Rather than going to an api call that just spits out json

**Comment by dpad85** [comment]
The `Open transaction in explorer` button was mainly added for debugging purposes, and for now we prefer having the raw json data instead of a web page because the web page does not directly display all the informations one could need.

The next step will be to let the user choose the explorer's url, with a default to a web client.

**Comment by dpad85** [comment]
A user preference for the onchain explorer has been added to Eclair wallet, this will be available in the next release.
