### ISSUE TITLE
Operator gets too little warning about channels in danger of closure.

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#1914]
It seems to me that the software has up to the 1-week-or-so punishment transaction deadline to warn its operator that "Eclair will force close channel XXXX because XXXX," but instead of providing any warning, it just closes it, leaving the operator to do an autopsy afterwards in the hope that s/he can learn enough to prevent a similar undesirable force-close in the future.

Some remedies to this would be to add a new state for a peer listing as the response to peers that indicates there is a problem which will be solved by channel closure unless something else changes. A good term for such a peer might be "faulty" or "warn". Of course, this is more appropriate for the channels API, in which each channel has a state. Ideally, whatever way this trigger-happy channel closure mechanism is altered to provide the operator with more warning will BREAK existing software that uses the API, as there is currently no obvious way for software using the Eclair-API to easily detect an imminent channel closure in time to give the operator time to save it, as far as I can tell.

I don't know how to reproduce the issue, but I did discover that the channel was closed due to "local/remote feerates are too different: remoteFeeratePerKw=4867 localFeeratePerKw=2009 while processing msg=CurrentFeerates in state=OFFLINE"

The closure was reasonable given my configuration for fee rate mismatch (0.5 - 10.0, which I have changed to 0.1 - 10.0), but the warning given to me about it (none at all) was not.  Is this a protocol issue regarding how much time already-negotiated fees are allowed to persist when one party requests a new negotiation?  The channel had been open for a very long time and therefore already had an closing fee policy that had worked.

This is "version": "0.6.1-d3ae323"

Windows 10, openjdk version "11.0.10" 2021-01-19

**Comment by t-bast** [comment]
> It seems to me that the software has up to the 1-week-or-so punishment transaction deadline to warn its operator that "Eclair will force close channel XXXX because XXXX," 

No, I think that's a misunderstanding.
You're misinterpreting the delay before which you can get your funds back in case of a force-close.
When a force-close happens, you need to wait before you're able to get your funds back, **but the force-close has already happened** (your commitment transaction has been broadcast / confirmed).

There's no delay during which we know we will force-close and are waiting for something, so there's no time during which we could show the channel as "this will force-close, node operator could do something".

> I don't know how to reproduce the issue, but I did discover that the channel was closed due to "local/remote feerates are too different: remoteFeeratePerKw=4867 localFeeratePerKw=2009 while processing msg=CurrentFeerates in state=OFFLINE"

We simply cannot give a warning here, because we react when we receive the information.
Eclair cannot guess that the feerate will not match anymore in X hours, because it can't predict the future.
It just sees that at some point the feerate doesn't match anymore, and to protect the safety of your funds it force-closes.
In your case it even seems that your peer was offline, which can be fishy.

This error is the main pain point triggering force-close, fortunately we know we will eventually be able to fully fix it at the spec level (with anchor outputs + package relay) but it's a big change that takes some time to implement securely.
