### ISSUE TITLE
`getsentinfo` returns an indeterminate response `[]`

### ISSUE THREAD

**Issue by fiatjaf** [ACINQ/eclair#2055]
`getsentinfo` may return `[]` because it doesn't know anything about the given `--paymentHash` or `--id`, which means a payment wasn't performed or attempted, and is not pending.

But it may also return `[]` for a payment that is in process of being attempted, for some seconds or fractions of second before it is actually attempted, which has the opposite meaning.

For services that send payouts automatically on behalf of users and then check these payment statuses automatically this can lead to terrible loss of funds.

**Comment by t-bast** [comment]
Right, the documentation is unclear for that API, it only returns results for payments once an HTLC has been sent out.
If you initiate a payment and call `getsentinfo` before the htlc is sent out (e.g. while path-finding is still running), you won't see that payment in the results.

We should probably ensure that all the `pay` commands never return before something has been written to the payments DB, which ensures it will appear in `getsentinfo`. We've chosen to return a response as soon as possible to callers of the `pay` API, but that probably wasn't such a good idea.

**Comment by fiatjaf** [comment]
After a payment is attempted will it stay on the DB forever?

**Comment by t-bast** [comment]
Yes, once attempted it will stay in the DB.
If you wait a couple of seconds after the `pay` command, I believe `getsentinfo` should always return something.

There can be an issue if you use `getsentinfo` *before* attempting a payment to check whether you already paid it, there is a race condition where multiple calls to `pay` for the same invoice may end up paying it multiple times.

Thinking about it more, even if we reworked the API to write to the DB before returning something to the caller, that race condition would still exist. The only way to completely remove that race condition would be to serialize payments, which would hurt throughput so it wouldn't be desirable in the general case.

What exactly are you expecting from this API, and how are you using it?

**Comment by fiatjaf** [comment]
I had a button on lntxbot that allowed users to check the status of their payments. If the payment failed it was deleted and the funds returned to the user balance. Users exploited this by clicking the button very fast just after sending the payment, then the response was `[]` and the funds returned. Later the payment would complete and I would lose money.

**Comment by fiatjaf** [comment]
I've fixed that by removing the button, but also by not doing anything when I get `[]`, just leave their status as pending.

However now I see that are some payments on my database as "pending", but when querying their status on Eclair (which I do on every restart) I get `[]`. I don't know what that means. Was this payment tried or not? I feel it must have been since it is on my database as "pending", but maybe something happened in between.

**Comment by fiatjaf** [comment]
So basically yes, I think you should only return from `payinvoice` after something was added to the database, that would improve things.

**Comment by t-bast** [comment]
> Users exploited this by clicking the button very fast just after sending the payment, then the response was [] and the funds returned.
> I've fixed that by removing the button, but also by not doing anything when I get [], just leave their status as pending.

Got it, thanks for the details. Damn!

In your case, you should always treat `[]` as `payment is pending` and spin and call `getsentinfo` again until the payment is settled (fulfilled or failed). Whenever a payment is attempted, there will **always** be a database entry added soon after (so `getsentinfo` will return something for that `payment_hash`).

If you're querying with the `payment_id`, make sure you're using the `parent_payment_id` (MPP introduces some complexity here).

Another option would be to use the `--blocking` option on `payinvoice`, which behaves similarly to c-lightning's default (the API only returns once the payment is settled). The issue is that if the payment is stuck at an intermediate remote node, the API will not return until the faulty node decides to fail the HTLC, which can create complex edge cases to handle on your side.

> I see that are some payments on my database as "pending", but when querying their status on Eclair (which I do on every restart) I get [].

That's very surprising, the only case where that will happen (and we can't do anything about it) is if you restart your eclair node after issuing a `pay` command but before path-finding completes. Then all record of this payment will be lost, and you can safely consider it aborted.

But if you're seeing this for payments where you didn't restart your node in-between, it would be an `eclair` bug and it would be nice if you could repro it (are you sure this isn't an issue of using a child `payment_id` instead of a `parent_payment_id`?).

Overall, after a restart, you can consider that payments that don't return anything in `getsentinfo` haven't been sent out - but beware which `payment_id` you call it with.

> So basically yes, I think you should only return from payinvoice after something was added to the database, that would improve things.

Actually I don't think it changes anything.
An attacker would just exploit the fact that there can be concurrent requests and you're back to the same issue.

The only way to properly address this issue is either:

- to consider `[]` as `pending` (which works in your case, since the button to check is only there if a payment was actually attempted - if we consider that potential eclair bugs are fixed) or `aborted` if the node restarted
- to have a database for this on your side, where you insert a row in the DB **before** making API requests which ensures you'll have all the info: it can only be done outside of eclair to be resilient to concurrency attacks (when I mean outside of eclair, it could be an eclair plugin). This is exactly why the `externalId` was added to the API, because @btcontract had a similar use-case and it lets the higher-level application reconcile its own database IDs with eclair's payment IDs

**Comment by fiatjaf** [comment]
> If you're querying with the payment_id, make sure you're using the parent_payment_id (MPP introduces some complexity here).

I've been querying with `paymentHash`. I've never seen that `parent_payment_id` thing anywhere. Is it the id we get in response from `payinvoice`?

> That's very surprising, the only case where that will happen (and we can't do anything about it) is if you restart your eclair node after issuing a pay command but before path-finding completes. Then all record of this payment will be lost, and you can safely consider it aborted.

It's probably caused by a restart then, I've been restarting the node too many times because of that other issue.

> Actually I don't think it changes anything.

I think it fixes it if I also not show any response to the attacker before Eclair has responded me. This way it's impossible for the attacker to try to check the payment (I mean theoretically, because in my case I will never expose that "check transaction status" button ever again, haha).

> to have a database for this on your side, where you insert a row in the DB before making API requests

I've been doing this, and also using `externalId` but mainly for manual reconciliation later (for example, the `externalId` was what allowed me to identify the payments that were made as part of the exploit after the fact).

**Comment by t-bast** [comment]
> I think it fixes it if I also not show any response to the attacker before Eclair has responded me. This way it's impossible for the attacker to try to check the payment (I mean theoretically, because in my case I will never expose that "check transaction status" button ever again, haha).

No, it doesn't protect you at all to hide the button, because nothing prevents a malicious user to just make the corresponding HTTP call even if there's not button, right? That's why I think it needs to be addressed in depth to be really safe, because if you leave a weak point, it will eventually be attacked, even if it's harder than just pressing a button.

I agree though that we should insert a "dummy entry" in the DB earlier, but there's a risk that it gives a false sense of security for services like yours, because it reduces the time frame where the attack is possible, but it is still possible. That's why I think we should properly document this, and maybe offer a plugin that uses this external DB and `external_id` to implement this use-case safely.
