### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#2085]
I would like to update the fees on a channel before it has completely opened. Currently, this requires that I edit the config file before I issue the open command because using updateRelayFee returns `"RES_FAILURE(CMD_UPDATE_RELAY_FEE( ... ),fr.acinq.eclair.channel.CommandUnavailableInThisState: cannot execute command=updaterelayfee in state=WAIT_FOR_FUNDING_CONFIRMED)`

What problems need to be solved so users can revise the record of what the base and rate-per-million fees should be for the node with which a channel is being opened?

**Comment by t-bast** [comment]
Actually, since #1890, I think that even though the API returns an error, the fees have actually been correctly updated since we update the fees DB first: https://github.com/ACINQ/eclair/blob/bacb31cf8d6db9ea323f0366a859686b632411ca/eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala#L199

When the channel funding confirms, the channel update that will be sent will use your updated fees.
I guess we simply need to update `Channel.scala` to stop returning an error here.
@thomash-acinq WDYT, am I missing something here?

**Comment by thomash-acinq** [comment]
Exactly, I'm removing the confusing error in #2086.
