### ISSUE TITLE
[Feature Request] Delay channel fee update until gossip has caught up

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#2110]
AFAIK c-lightning and LND already implemented a feature where raised channel relay fees taking effect is delayed by 10 minutes or so to avoid routing failures and give the update message enough time to propagate through the gossip network.

If possible, this should come with an option to optionally enforce the new fee right away, when routing failures are preferred over a quickly depleted channel, i.e. when a channel was opened with an erroneously low fee.

Thinking about it, even lowering fees should come with a delay, to have time to fix typos that caused a way to low fee.

**Comment by t-bast** [comment]
I think this makes sense, we can simply be lenient and keep accepting our previous fees for up to X minutes.

To keep it simple, we can make this an in-memory-only feature: we keep that information locally but if eclair restarts, we don't guarantee that we will allow old fees.

**Comment by remyers** [comment]
The equivalent issue in c-lightning is [#4761](https://github.com/ElementsProject/lightning/issues/4761). This issue was fixed by adding the `enforcedelay` grace period (default 10 minutes) before enforcing a change using `setchannelfee`.

I could not find the equivalent feature in LND, anyone have a link?

**Comment by remyers** [comment]
Implemented with PR #2201
