### ISSUE TITLE
Can´t use my Eclair since "Sunset Notice" was diplayed

### ISSUE THREAD

**Issue by GranpaJuanito** [ACINQ/eclair#2223]
Hi there. 
Cant make any movement on my wallet since March 25th Images attached. All channels are closed & cant open anyone from the 4 options given (Paste or scan nodes URI do not work from LN explorer, Random node say me BOLT 10 "Not available yet" & last one, ACINQ node gives me a message "Failed to open channel: peer sent error" Some ACINQ reply to my first tweet toldme to send my NodeID to "Helloacinq.co" Mail already sent no answer yet.
Thanks in advance 4 any help on this.

![OpeningNode](https://user-imag
![Surprise](https://user-images.githubusercontent.com/102921621/161443264-d6e12978-ea6e-418d-a75c-74d7c0865761.jpeg)
es.githubusercontent.com/102921621/161443255-1d67f74b-4445-4132-bd1a-28a235641ea3.jpeg)
![Expensive](https://user-images.githubusercontent.com/102921621/161443275-b11e0c84-6a7a-415b-a958-ad166fc5bfee.jpeg)

**Comment by t-bast** [comment]
Have you considered switching to https://phoenix.acinq.co/ ?

**Comment by GranpaJuanito** [comment]
Yes I did, but can not use my Eclair recovery 12 words on Phoenix (closed channels + not passphrase on Phoenix))

**Comment by t-bast** [comment]
> send my NodeID to "Helloacinq.co" Mail already sent no answer yet.

It looks like you never did that, we never received any mail with your `nodeId`.

> Yes I did, but can not use my Eclair recovery 12 words on Phoenix (closed channels + not passphrase on Phoenix))

I don't understand what you mean.
If all your channels are closed in your eclair-mobile wallet, then you only have on-chain funds (nothing in lightning channels).
That means you can simply create a completely new wallet on Phoenix, and then send all your funds from eclair-mobile to Phoenix.
This will be much easier to use for you in the future than eclair-mobile, so I strongly recommend doing this.

**Comment by dpad85** [comment]
> But on Eclaire? How can send funds from onchain part of the wallet?

You do it just as you would do with any LN payment:

1. In Phoenix, go to Receive > "Show a Bitcoin address", and copy the address that has been generated
2. In Eclair Mobile, click on the blue arrow button, in the bottom-right corner of the app, then "Paste a payment request"
3. Enter the amount you want and click Pay. Note that the "Empty wallet" checkbox makes Eclair Mobile compute the exact amount to send so that the balance of Eclair Mobile ends up at 0 (no dust left on the wallet).

If you still have open LN channels on Eclair Mobile, you will have to close them first, otherwise those funds will remain.
