### ISSUE TITLE
Eclair cant keep up with Core

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#2259]
My node constantly sends `DangerousBlocksSkew` events while apparently late on tip.

The node shouldn't be late.

In particular situation I've seen `735008` in output of `getinfo` while Core API was returning `735015` from the same host where Eclair is installed.

I've seen such behavior several times and verified additionally by curling Core API. The Bitcoin client has been in sync always.

To reproduce the issue one supposedly should have remotely operated Core node in VPN network.

Compiled, `0.7.0-a804905`.

Server with Linux OS installed.

**Comment by t-bast** [comment]
Eclair's behavior is to:

- receive blocks over zmq socket
- if no blocks have been received for 15 minutes, actively request them from `bitcoind`

The second point is here to compensate failures to receive on zmq (which can happen on unreliable networks).

Here is the median time when these blocks were founds (taken from `mempool.space`):

- 735008: 2022-05-05 12:56
- 735009: 2022-05-05 13:28
- 735010: 2022-05-05 13:30
- 735011: 2022-05-05 13:31
- 735012: 2022-05-05 13:41
- 735013: 2022-05-05 13:42
- 735014: 2022-05-05 13:47
- 735015: 2022-05-05 13:53

Notice that there is a long delay between block 735008 and 735009, then three blocks are found very close to each other.
In your case, we've seen that your network is quite unreliable, so you're probably not always receiving blocks over the zmq socket and instead relying on eclair actively fetching them from `bitcoind` every 15 minutes. You also probably have a small delay in receiving blocks compared to the best connected nodes in the network (such as explorers, which we use as watchdogs). That means there will be some time during which you will be behind the tip, which explains why you're seeing `DangerousBlocksSkew` events.

In your case they're not really dangerous, because you're getting back to the tip every 15 minutes, and an attacker cannot find enough blocks in 15 minutes to exploit this. But we will still emit the events because they reflect reality, and because eclair cannot know that you have an unreliable network and that it should be more lax. However, this is not an issue: emitting these events is here to help node operators ensure their setup works correctly. It doesn't mean something isn't working properly inside eclair. If you can't make your network more reliable, you can tweak eclair to be more lax about these events, by for example changing `BlockchainWatchdog.scala` to use a delta of 12 blocks instead of 6 [here](https://github.com/ACINQ/eclair/blob/69589706d3c79f162d43d5620795035c5bfdc26a/eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala#L118). Or even better, you could contribute to `eclair` by making this field configurable, which would let you choose the right value depending on how your node is setup.

**Comment by t-bast** [comment]
@engenegr any update on that issue? Let us know if you want to make this delta configurable or not, otherwise we'll close as inactive.

**Comment by engenegr** [comment]
@t-bast I did the changes along other related to batching. Not fully tested yet because exactly this option I need more on mainnet node, not on the testnet node where most of the testing happens.

**Comment by engenegr** [comment]
I opened a PR.

**Comment by t-bast** [comment]
Fixed by #2301
