### ISSUE TITLE
MAX_FUNDING_TX_ALREADY_SPENT issue with some other node implementations.

### ISSUE THREAD

**Issue by DerEwige** [ACINQ/eclair#2335]
fry/acinq/eclair/io/PeerConnection.scala

Tested version:
Eclair v0.7.0

Description
When MAX_FUNDING_TX_ALREADY_SPENT is reached eclair will not request any more channel announcements from the connected node for 60s.
Some nodes interpretate this pauses as a problem and close and then reopen the connection.
This causes eclair to restart the retrieval of the channel announcements.
Running again into the MAX_FUNDING_TX_ALREADY_SPENT threshold and restart the whole thing.
This leads to a cycle as the behaviour of éclair and the other node are incompatible.

Reproducing steps
Open a channel with node  038fe1bd966b5cb0545963490c631eaa1924e2c4c0ea4e7dcb5d4582a1e7f2f1a5@144.76.24.71:9735

Possible Solution:
Increasing the MAX_FUNDING_TX_ALREADY_SPENT solves this issue.
I’ve compiled my own version with a value of 1000 instead of 10.
Also created a version to read the value from the config file

**Comment by t-bast** [comment]
Why does your peer send you channel announcements for channels that have been closed? That is a bug that they should fix and is the root cause of the issue, isn't it? That really looks like something they should look into, because eclair correctly interprets this as bad behavior (this is effectively spam).

> Some nodes interpretate this pauses as a problem and close and then reopen the connection.

Why would they? If we don't want to request channel announcements from them it's entirely our choice, they shouldn't interpret it and should definitely not disconnect...I may be missing something here, can you provide more details about this?

We can make this parameter configurable if you want, but it does indicate a buggy/spammy peer, so I'd rather address the real root cause here.

**Comment by t-bast** [comment]
> It is not the channel that is closed it is just the connection to the node.
So the peer goes from state “CONNECTED” to “DISCONNECTED”

Yes I understood that, but it doesn't change the point that it's mostly a bug on their side that should be fixed?

You can also stop syncing the graph with that node if they're sending you spam data, by using the `sync-whitelist` in your `eclair.conf` (https://github.com/ACINQ/eclair/blob/af79f44051a08ecc31eab5a129d41e6c3100776a/eclair-core/src/main/resources/reference.conf#L77)

**Comment by DerEwige** [comment]
I try to find out which implementation they are using and open a issue there.
It would still be nice if the value would be configurable.
Thanks for your time

**Comment by t-bast** [comment]
We can also make this configurable if that's helpful, even though I would recommend just not syncing gossip with peers who send you invalid data like this (and instead use the `sync-whitelist` to select only a handful of good peers to sync gossip from).

**Comment by DerEwige** [comment]
@t-bast 
The issue can no longer be reproduced.
I've talked to the owner of the other node and he upgraded to the newest version of CLN.
It looks like they fixed it on their end.
