### ISSUE TITLE
incompat b/t lnd 0.15.1 & eclair 7.0

### ISSUE THREAD

**Issue by Crypt-iQ** [ACINQ/eclair#2412]
Hi I believe this is because 0.7 eclair nodes used trampoline payment feature bits 50/51. So when they connect to LND nodes, the 0.15.1 LND nodes will interpret bit 51 as zero-conf, which requires scid-alias. The older eclair nodes don't have scid-alias set, so LND will fail the init handshake since zero-conf requires scid-alias to be set.

for ref: https://github.com/lightningnetwork/lnd/issues/6880

Not sure that anything can be done besides older eclair nodes upgrading

**Comment by t-bast** [comment]
Indeed, this is an issue for older nodes, we updated that once we saw that the zero-conf PR was using the same feature bits.
We've made a release of eclair on July 18th that contains the fix, I'm surprised some node operators are still on an older version, especially since that release was just a minor patch release (no reason to delay upgrading).

However, for node operators that are stuck on old versions, they should set the following in their `eclair.conf` to fix this issue:

```conf
eclair.trampoline-payments-enable=false
```

**Comment by EagleTM** [comment]
Hi, I'm running eclair-node-0.7.0-patch-disconnect-cad88bf from July 18 however, connecting to lnd 0.15.1 still prompts the following error message on the lnd side: 

2022-09-24 16:37:14.077 [INF] PEER: Peer(): disconnecting <peerid:ip:port>, reason: unable to start peer: invalid remote features: missing feature dependency: 47

Unfortunately I believe the issue is not fixed with the latest release. Is there an easy way to test master (i.e. builds of that ready to run?)

I'm running with (excerpt from eclair.conf)

trampoline-payments-enable=true
  features {

     trampoline_payment = optional
     option_support_large_channel = optional
     option_anchor_outputs = optional
     option_anchors_zero_fee_htlc_tx = optional
     option_zeroconf = disabled
     trampoline_payment_prototype = disabled
  }

**Comment by EagleTM** [comment]
I managed to build master with maven and am running eclair-node-0.7.1-SNAPSHOT-b00a0b2 . 

I can confirm it's working to connect to lnd 0.15.1 with this version. However that may be because " trampoline_payment = optional" is not supported in this version and has to be taken out. I'm assuming / hoping trampoline-payments-enable = true and trampoline_payment_prototype = optional does the same thing?

**Comment by t-bast** [comment]
> trampoline-payments-enable=true

Why would you ever enable trampoline payments? This is useless except for our own node, because Phoenix leverages it. Activating it on your node is useless, nobody will actually use your node to relay trampoline payments as there is no built-in gossip mechanism for now. It's only a prototype at this point since the specification effort is still ongoing, and we will break backwards-compatibility on the trampoline onion format once the spec converges.

This really isn't a feature that is meant to be activated by normal eclair nodes, you should just disable it (as the default configuration does) and you won't have any compatibility issue.

**Comment by EagleTM** [comment]
> > trampoline-payments-enable=true
> 
> Why would you ever enable trampoline payments? This is useless except for our own node, because Phoenix leverages it. 

Electrum ( https://github.com/spesmilo/electrum/search?q=trampoline) actually makes use of this in its LN implementation as of release 4.1.0 (March 2021) and I believe it's the default mode now for new installations starting to use LN. Indeed, there are very few trampoline enabled nodes on the network as eclair is the only implementation for now.

Using 0.7.1 from master and trampoline-payments-enable=true works opening new trampoline channels with Electrum and routing trampoline (and connecting to 0.15.1 lnds).

For everyone running 0.7.0 and not supporting Electrum trampoline it's fine to just disable trampoline to connect to lnd 0.15.1 indeed.

**Comment by t-bast** [comment]
> Electrum ( https://github.com/spesmilo/electrum/search?q=trampoline) actually makes use of this in its LN implementation as of release 4.1.0 (March 2021) and I believe it's the default mode now for new installations starting to use LN. Indeed, there are very few trampoline enabled nodes on the network as eclair is the only implementation for now.

I thought Electrum was only using a hard-coded set of trampoline nodes that they controlled...eclair's current trampoline implementation isn't meant to accommodate this, and won't share fees and cltv in `node_announcement` as they seem to expect. In practice I don't expect this to work very well, are you actually seeing trampoline traffic on your node?

Since we didn't think anyone was actually turning this on, we haven't made a release for the feature bit migration. We have pending changes we're working on at the moment (dual funding, blinded paths, etc) so we can't easily make a release now that contains the fix, but we'll try to do one as soon as possible. Meanwhile, if you still want to enable trampoline and are fine running on `master`, this should indeed fix the issue. But beware that the trampoline implementation could change in a backwards-incompatible way in the future (even though we're trying to minimize that as much as possible).

**Comment by EagleTM** [comment]
My node is part of the hard coded set and that's why I'm seeing trampoline payments. Hardcoding won't change for a long as trampoline is not widely used  / implemented, indeed. I guess all Electrum clients need is the feature bit that it's actually a trampoline routing node and that works fine.

I agree this is special use and no worries that there is no release for this. Thanks for all the work on eclair and thanks for the heads up that the implementation could change. I guess it's also useful to know it's being used outside of phoenix for trampoline routing.

**Comment by EagleTM** [comment]
Update:

For eclair-node-0.7.0-patch-disconnect-cad88bf it appears sufficient to remove
`trampoline_payment = optional`
to be able to connect to 0.15.1 and still have `trampoline-payments-enable` (if you're part of the electrum trampoline server set)

**Comment by t-bast** [comment]
Yes, that simply migrates trampoline to using the new experimental feature bit (148/149) instead of the conflicting one (50/51).

**Comment by ecdsa** [comment]
I am running eclair-node-0.7.0-a804905 on the main Electrum trampoline.
I have `trampoline-payments-enable = true` and  `trampoline_payment = disabled` in the `features` section, as described above, and I can connect to LND.

My issue is that bit 51 is still set in the invoices created by Eclair with the above config. 
This should not be the case.

As a result, LND refuses to pay the invoice:
`2022-10-27 06:04:05.479 [WRN] CRTR: Pathfinding destination node features: missing feature dependency: 47`
I noticed that when trying to rebalance a channel between Eclair and LND.

**Comment by t-bast** [comment]
This has been fixed on `master` and we should have a release out in the next couple of weeks.
