### ISSUE TITLE
Problem with connect to dynamic IP

### ISSUE THREAD

**Issue by vadimVoloshanov** [ACINQ/eclair#246]
Hello, i tested your aplication and saw what in tab "All nodes" don`t showed "IP"
![pasted_image_at_2017_11_30_01_54_pm](https://user-images.githubusercontent.com/30472334/33427853-dc1298f0-d5d7-11e7-92e3-7c67428ecc74.png)

Also i can`t connect to my friend with dynamic ip, for what reason is this and whether there will ever be such an opportunity?

**Comment by EndrII** [comment]
Same problem.
Bitcoin version: 0.15.1
Branch: master

**Comment by dpad85** [comment]
Hello, you need to set a public ip for your node in the `eclair.conf` file. By default the node does not announce a public IP, that is why the field is empty in the list.

For example in `eclair.conf`
```
eclair.server.public-ips.1=127.0.0.1
```

To accept incoming network connections, a node must announce a public IP.

**Comment by EndrII** [comment]
this does not solve the problem.
We need to create a connection between two users with dynamic ip.

example :
Alisa : start eclair on PC  with 192.168.1.3 
gateway : 167.122.6.70 - it is not global ip, it is first gateway server 
network mask : 255.255.255.0
public ip 213.184.225.234

so network route : 192.168.1.3  >> 167.122.6.70 >> ... >> 213.184.225.234



Bob : start eclair on PC with 192.168.1.1  
gateway : 17.127.6.33 - it is not global ip, it is first gateway server 
network mask : 255.255.255.0
public ip 213.184.215.131

network route : 192.168.1.1  >> 17.127.6.33 >> ... >> 222.84.125.34

Alice tries to open the channel by using the entry:

pubKey@222.84.125.34:9735
but the channel is not created because the eclair is physically located elsewhere.

The same problem is with Bob.

How to solve this problem?

This is a critical problem.
it urgently needs to be solved because there is a need to create channels without static ip.

**Comment by EndrII** [comment]
Are you having a solution for my problem?

**Comment by pm47** [comment]
Hello @EndrII,

Qualifying your issue as "critical", needs urgent fixing and adding follow up messages with no value does not help get it solved.

What would help is clearly describe your problem, which you haven't done yet. Is it:

1) that Alice can't open a connection to Bob at all
or
2) that Alice can open a connection to Bob once, but has trouble maintaining the connection because Bob's public ip is dynamic and regularly changes

**Comment by EndrII** [comment]
Alice can't open a connection to Bob at all.

**Comment by pm47** [comment]
Alright, so this is not related to dynamic ips.

You need to configure Bob's router, so that it forwards connections on port 9735 to 192.168.1.1:9735. Aka NAT. It is very similar to what's needed for bitcoin core (see [documentation](https://bitcoin.org/en/full-node#port-forwarding)), except that it is port 9735 instead of 8333. 

Note that if you are having trouble doing that, you shouldn't probably be trying to run an alpha-version software like Eclair.

**Comment by pm47** [comment]
Closing the issue, assuming that the :+1: meant it worked.
