### ISSUE TITLE
Running multiple backend nodes for high availability

### ISSUE THREAD

**Issue by gcool-info** [ACINQ/eclair#2578]
When looking at https://github.com/ACINQ/eclair/blob/master/docs/Cluster.md, it seems like you can run multiple frontend nodes but only one backend one.

Is it possible to run multiple backend nodes in active/active setup?

**Comment by t-bast** [comment]
No, this is currently not possible. It's something to explore, in theory it would be useful in case of hardware failures on the backend machine. I'm not sure how much work would be required to make this work though.

**Comment by gcool-info** [comment]
Thanks @t-bast !

And a quick follow-up: is it possible to run them in active/passive mode perhaps?

**Comment by t-bast** [comment]
No, not yet either. This could create subtle issues that affect the safety of the node, so this is probably not trivial to do.

**Comment by t-bast** [comment]
Right, I remember that @rorp! You're right, the active/passive mode can trivially be implemented by abusing the DB lock.

It shouldn't be too hard to make this a bit cleaner, by starting the passive node with a `--passive` flag, and when it is set, the node just loops trying to get the DB lock every X seconds.

I think we'd favor an active/passive mode over an active/active mode for lightning, it's easier to deploy and safer with regards to channel state. As @rorp shows, this can be done today, and small changes can make that even more straight-forward, so I'll close this issue for now (it would have made more sense as a [discussion](https://github.com/ACINQ/eclair/discussions) rather than an issue BTW).

**Comment by gcool-info** [comment]
Thanks for the help! 

Noted for the discussion, for next time :)
