### ISSUE TITLE
How to get dust into a p2sh-of-p2wpkh?

### ISSUE THREAD

**Issue by AndySchroder** [ACINQ/eclair#287]
In README.md you say

> On testnet, you also need to make sure that all your UTXOs are p2sh-of-p2wpkh.

How is one to do this if some of their UTXOs are dust? Why can't you just require one UTXO to be p2sh-of-p2wpkh?

**Comment by pm47** [comment]
> How is one to do this if some of their UTXOs are dust?

Good question! @sstone any idea?

> Why can't you just require one UTXO to be p2sh-of-p2wpkh?

Because then we would have to know about it and explicitely ask to spend this particular output when creating transaction, whereas currently we just let bitcoin core choose whatever utxo it wants. We just went for the easiest solution.

**Comment by AndySchroder** [comment]
So, I was able to work around this issue by taking a non-dust p2sh-of-p2wpkh UTXO and a dust P2PKH UTXO and send them in a single transaction to a p2sh-of-p2wpkh.

**Comment by sstone** [comment]
>  How is one to do this if some of their UTXOs are dust?

Well, the trick that we mention in our README ("create a witness address and send all your balance to this witness address") should have worked even if some of your utxos were dust. Did you try and if so was one of your dust utxos left behind ?
If you prefer to select and combine utxos manually and you only have a few utxos that still sum up to dust, then yes you'll have to combine them with non-dust utxos (and then don't forget to specify a segwit change address too :))

This should became much easier once Bitcoin Core's wallet fully suppports segwit (maybe in the upcoming 16.0 version ?)

**Comment by AndySchroder** [comment]
I don't really remember how I got a dust transaction in the first place, but I'm thinking this is even less chance of being an issue now that version 0.16 of bitcoin core has been released.

Still though, why do you even have this requirement in the first place? It is unclear if this will also be a requirement once you reach a mainnet release. Why can't you make it smart enough to avoid these non segwit UTXOs?

**Comment by sstone** [comment]
We added this requirement because we don't want to create malleable funding transactions and before 0.16 it meant asking users to maintain all their UTXOS as p2sh-of-p2pkh which in turns means specifying change outputs manually whenever you create a transaction, which is very inconvenient.

We could have had a smarter implementations which only selects UTXO that are p2sh-of-p2pkh but it is more complex, error prone and confusing ("LN node says I don't have enough funds but wallet says I have plenty"), and not needed anymore .

We will drop support for older bitcoin core versions with our upcoming beta, which will be our first "mainnet" release, and ask users to run 0.16 with address-type set to `p2sh-segwit`, and they won't have anything else to do.
