### ISSUE TITLE
How do I broadcast my IP on the Lightning Network

### ISSUE THREAD

**Issue by resdat** [ACINQ/eclair#289]
I have a Lightning testnet node up and running using Bitcoin Core and Eclair for Windows. I can send and receive, and find my Pubkey. The one last thing I would like to do is show up on the map, which is not happening since it says I have no public IP. I assume that this is a config parameter I can add to eclair.conf, but I cannot find it. 

How do I broadcast my IP address so I show up on the map?

**Comment by resdat** [comment]
Just for clairification, I was looking on the Lightning Testnet  Explorer https://explorer.acinq.co/#/

**Comment by drmoore718** [comment]
Open up the port (default 9735) and set your external IP into the ~/.eclair/eclair.conf file.

public-ips = [ "a.b.c.d" ]

See https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/resources/reference.conf for reference configuration.

**Comment by resdat** [comment]
Thank you for the quick response, but it still is not working. I added the line

elcair.server.public-ips = ["24.237.204.10"]

I also tried it without the eclair.server. part, as you suggested. Both seemed to work without causing any errors. I have port 9735 open for TCP/UDP but it still shows as No Public IP. I changed my alias name from resdat2 to resdat3 in eclair.conf, and that changed so it does not seem to be an issue with refresh time. Here is my current eclair.conf file:

eclair.server.port=9735
elcair.server.public-ips = ["24.237.204.10"]
eclair.node-alias=resdat3
eclair.node-color=49daaa
eclair.bitcoind.rpcuser=xxx
eclair.bitcoind.rpcpassword=yyy

Any ideas?

**Comment by drmoore718** [comment]
You do need the eclair.server. part like you have it.  I just have mine inside the curly braces like how it's done in the reference.conf.  

Your config looks fine from what I can tell - those steps worked for me.  I don't have any other ideas other than perhaps giving it some more time or double-checking your port forward.

I asked the same question yesterday so I'll post what one of the devs' response in case it helps.

drmoore718 @drmoore718 Dec 15 08:28
To have a public IP do I need to open a port?

Pierre-Marie Padiou @pm47 Dec 15 08:36
your ip is whatever you see on http://whatismyip.org/
in order to allow people to connect to your node, yes you need to open a port in your router (just like for bitcoin core see https://bitcoin.org/en/full-node#network-configuration but port 9735 instead of 8333)
finally if you want to advertise your node on LN and have people connect to it, you need to tell eclair your public ip by setting eclair.server.public-ips.0=a.b.c.d in eclair.conf
if you do all that and open a channel your node will appear on explorer.acinq.co

**Comment by resdat** [comment]
What does yours look like exactly? When I use {} which is what I would call curly brackets, it gives me an error. I am able to transfer bitcoin to and from the eclair app, and I can change my node-alias and node-color and they show up in the explorer, but it always says No Public IP.  I have tried TCP and TCP/UDP port forwarding, and confirmed the number is correct without any luck. I double checked whatismyip.org, and even the geolocate service that they use and it shows my address is in Girdwood AK, which is correct.

**Comment by pm47** [comment]
@resdat you were almost there but did a typo, it's **eclair** not **elcair**.

Correct conf is:
`eclair.server.public-ips = ["24.237.204.10"]`

For that kind of troubleshooting, please use our [gitter](https://gitter.im/ACINQ/eclair) instead, you'll get a faster answer.

**Comment by kalimagic** [comment]
I'm running the lightening node that i compiled on a windows machine, how do i broadcast my ip, do i need to port forward and if so to where. Keep in mind im not running eclair.
