### ISSUE TITLE
Feature Request: Request payment via lightning in Android App

### ISSUE THREAD

**Issue by PRabahy** [ACINQ/eclair#302]
I couldn't find a way in the android app to request tBitcoin via lightning. If I swipe left, it gives me a traditional address and QR code, but that requires a transaction on the blockchain.

**Comment by sstone** [comment]
This is by design, for now the mobile app can only pay on LN, which makes it safe to use even if the phone is offline most of the time. Receiving payments is on our roadmap but we'll need to deploy our monitoring solution first. There is a more detailed explanation [there](https://medium.com/@ACINQ/announcing-eclair-wallet-a8d8c136fc7e) but the gist of it is that to receive LN payments you need to monitor the blockchain, detect cheating attempts and react. This would be difficult on a device that is often offline, but can be delegated to a third-party watcher without loss of privacy and very little trust.

**Comment by Sgt-Miller** [comment]
For more info refer point 3 here :
https://github.com/lightningnetwork/lightning-rfc/blob/master/05-onchain.md

**Comment by dpad85** [comment]
Moved this issue to the eclair-wallet repo (https://github.com/ACINQ/eclair-wallet/issues/48).

**Comment by ParmuSingh** [comment]
Still waiting..
