### ISSUE TITLE
Eclair Android hard crash at startup on network issue

### ISSUE THREAD

**Issue by PRabahy** [ACINQ/eclair#307]
Oh no.. Every time I try to start Eclair android, I get the splash screen, then "Eclair Wallet Testnet has stopped. Restart App?"

**Comment by PRabahy** [comment]
Ah, wifi was messed up (connected, but no internet connection). When I turned off the wifi, it stopped crashing.

**Comment by dpad85** [comment]
The way eclair mobile is started is going be reworked for several reasons. This will also prevent hard crashes at startup, the application will fail gracefully and try provide some valuable feedback to the user, when possible.

Now the problem here is probably a networking issue causing a timeout. We will look into it! Thanks

**Comment by dpad85** [comment]
A fix for this issue will be available in the next release (0.2.4).

**Comment by dpad85** [comment]
0.2.4 is now available and fixes this issue.
