### ISSUE TITLE
Wrong error message for payments below 10sat

### ISSUE THREAD

**Issue by Sgt-Miller** [ACINQ/eclair#315]
[Eclair desktop wallet, regtest with Bitcoin Core]       
Situation - A and B have a channel with funds (2 mBTC, 2mBTC).    
B requests payment of 1 sat.  
A tries to send.        
What happens : Notification on top right : Route not found.  
What should happen : The error should say "Less than minimum amount".    
I think this is the relevant part : 
https://ghostbin.com/paste/ns5nw

Or does it mean to say "No route which supports such a tiny amount was found"?
I think it should be a distinct notification, not the usual "Route not found".
Also, is there a reason why 
` htlc-minimum-msat = 10000`   
by default and not 1? (I'm not very familiar, I assume this config line is what says you can't pay less than 10 sat? )

**Comment by dpad85** [comment]
`htlc-minimum-msat = 10000` is retrictive, it should be 1 by default, i'm making a PR in that sense. You can override this value in `eclair.conf`.

The 'Route not found' message is not an error. When you send a payment, multiple attempts are made (5 by default). The first attempt fails because your only channel `A` -> `B` requires htlc to have `amount > 10000 msat` (10 sat). If only 1 attempt was allowed, the displayed failure message would be adequate. 

The second attempt fails because the `A` -> `B` channel is now ignored and there are no other available channels. The displayed error message is then 'Route not found'.

The problem here is to display an exhaustive yet readable list of of the errors - if the payment has failed.

**Comment by dpad85** [comment]
Fixed by https://github.com/ACINQ/eclair/pull/431
