### ISSUE TITLE
Please list when network explorer was last updated

### ISSUE THREAD

**Issue by AndySchroder** [ACINQ/eclair#339]
The website https://explorer.acinq.co has had the same number of nodes and channels listed on it for days. It appears as though this is not real time data, but the web page leads the viewer to believe it is. Please list somewhere when the data was last updated. This is useful whether it is updated automatically, or manually.

**Comment by 6hundred** [comment]
i second that. node and channel counts are way too off on explorer.

**Comment by pm47** [comment]
> It appears as though this is not real time data, but the web page leads the viewer to believe it is.

The explorer is actually updated automatically every 10 minutes, but has been unreliable during the holidays, mainly because the node it was getting its data from was flaky. So just giving a timestamp wouldn't help.

Note that from the pov of the explorer, there is no way to be sure that it is not missing data (there is no way to actually guarantee that, since the network can be partitioned anyway). Yes we could make it more reliable by fetching data from various sources.

Please consider it just a tool, not a source of truth.
