### ISSUE TITLE
Eliminated PENDING payments don't become FAILED on uncooperative close

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#342]
![photo_2017-12-26_07-58-54](https://user-images.githubusercontent.com/9870980/34348368-cc42876a-ea12-11e7-9a20-244a97961111.jpg)

Three PENDING payments on a screenshot are from two uncooperatively closed channels. Given the 53,000 SAT/kw feerate at least two of them are definitely eliminated and can't be redeemed on-chain, yet they are not marked as FAILED.

Both payment channels are CLOSED and removed at this point, it was a remote uncooperative close in both cases.

One HTLC's value can't be seen on a screenshot, it's 0.042 mBTC.

**Comment by pm47** [comment]
Can you give me the funding tx id of these channels?

**Comment by xela22** [comment]
I confirm, I have the same issue.
2 "PENDING" transactions (paid to yalls.org) on uncooperative close(not by me).

**Comment by dpad85** [comment]
It might be an UI issue here. If a payment is pending and you close the application before resolution (success or fail) the UI does not refresh the status of the payment once you restart the application, even though the HTLC is completed.

So in this case the total balance would be correct (since it is pulled directly from eclair-core) but the interface tells you there is a problem.

**Comment by dpad85** [comment]
The fix for this issue will be available in the next release (0.2.4).

**Comment by dpad85** [comment]
0.2.4 is now available and fixes this issue.
