### ISSUE TITLE
[mobile] getting ERR_FUNDING_PUBLISH_FAILED when trying to connect to several nodes

### ISSUE THREAD

**Issue by ric2b** [ACINQ/eclair#373]
**Not all of my attempts failed!**

I'm using 0.2.3 for Android.
I was trying to open channels with well connected nodes on https://explorer.acinq.co

Here's the nodes that I tried to connect to and failed with ERR_FUNDING_PUBLISH_FAILED:
- [03dc39](https://explorer.acinq.co/#/n/03dc39d7f43720c2c0f86778dfd2a77049fa4a44b4f0a8afb62f3921567de41375)
- [02d28c](https://explorer.acinq.co/#/n/02d28c3aac4b4f36746052a735831afbe65bc5698a7be5bd41b42fd1ddf2a1a358)
- [02c399](https://explorer.acinq.co/#/n/02c39955c1579afe4824dc0ef4493fdf7f3660b158cf6d367d8570b9f19683afb5)
- [03987a](https://explorer.acinq.co/#/n/03987a79dfd6089487cc8b3611a94fda8e21a927cd0a0cf381193491b62a7e7190)
- [022c31](https://explorer.acinq.co/#/n/022c315d7588cf1714159915baae386dc87462b669a7036df33850e9c0a3265893)
- [02d2cc](https://explorer.acinq.co/#/n/02d2ccdf98507238b7980c94616815ad2fec75f048caeaba738f408da363e43ba1)
- [02f892](https://explorer.acinq.co/#/n/02f892835902bdf1686ba96e733aec52105e68c0a312daec7ad08adc4d3927e4e2)
- [02464b](https://explorer.acinq.co/#/n/02464bfaaae78b98268a6a6d7e8f6a110c60dd1293811d6029b11ee9edb4bbf869)

Node [0298d0](https://explorer.acinq.co/#/n/0298d0c6987e2e64451c7f723e15aff4dfca92f0e3973d214e206257abb0d1dd55) seems to be stuck on WAIT_FOR_ACCEPT_CHANNEL

I **was** able to open channels with: 
- [03f113](https://explorer.acinq.co/#/n/03f113414ebdc6c1fb0f33c99cd5a1d09dd79e7fdf2468cf1fe1af6674361695d2)

I also have a channels open with [Y'alls](https://explorer.acinq.co/#/n/02ecafd1d828301da58edacdd61232835940c91767a01b3bfba57240989f9df4da) and the default node ([Endurance - 039338](https://explorer.acinq.co/#/n/03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134)) and am able to make payments so the wallet is mostly working. 

I tried to find any information on what ERR_FUNDING_PUBLISH_FAILED means but I can't find any issues (open or closed) about it and I can only find about 3 lines on the code itself so I don't think this is something one would expect to see happening.

**Comment by ric2b** [comment]
I tried restarting the App and it's been very laggy for the last minute or two, with the states of all of these channels bouncing around between OFFLINE, SYNCING, WAIT_FOR_FUNDING_CONFIRMED and NORMAL (only a few of them are on NORMAL)

**Comment by pm47** [comment]
Hello,

Thanks for this detailed report. It looks like a collection of different issues:
- `ERR_FUNDING_PUBLISH_FAILED`: this means that the wallet couldn't publish a funding transaction. I would say the issue was a connectivity problem with the electrum server we use as wallet backend. Your money should not be lost, since it wasn't spent. In the tx history, there shouldn't be any outgoing on-chain transaction for these failed channels. Can you check your tx history and see if that's the case?
- status blinking between `NORMAL`/`OFFLINE`/`SYNCING`: a related issue has been fixed, but not yet released
- general lag: this is most probably due to routing table sync. Our strategy so far was extremely naive (full sync at every connection), and needs improvement. We are working on it.
- node stuck in `WAIT_FOR_ACCEPT` state: the problem isn't on your side, but on the remote node you are connecting to and which isn't responding. It could also be a consequence of the previous point: there are so many routing messages that the `accept` message can't immediately go through.

**Comment by ric2b** [comment]
Thanks for the response :)

I'm guessing there's an issue with how the wallet handles "ERR_FUNDING_PUBLISH_FAILED" then, because all of those channels are still stuck on the uncooperative close, which shouldn't even be possible if the channel wasn't open in the first place, right?

About the lag, it's bad enough that it only gets like 1 frame every 2 seconds when scanning QR codes. Before I tried to open all of those channels it was fast and smooth as expected. I just sent a few reports from Android when it asked me if I wanted to kill the app or wait for it to respond, maybe they can be useful to track down the perf issue?

**Comment by pm47** [comment]
What's the brand/name of your device?

**Comment by ric2b** [comment]
It's a bq aquaris m5, running Lineage OS (android)

**Comment by pm47** [comment]
State `ERR_FUNDING_PUBLISH_FAILED` has been removed by ea9c005fe8a9920015e20c5cb0568c50e1edbfba.

Issue #454 tracks the `WAIT_FOR_ACCEPT` problem.
