### ISSUE TITLE
[mobile] hundreds msatoshis displays as 0.00mBTC Payment

### ISSUE THREAD

**Issue by AndWav** [ACINQ/eclair#397]
ver: 0.2.3

Invoice with 500 msatoshis is displayed as 0.00mBTC in payment confirmation dialog.
As "Amount paid 0,0001mBTC" and "Amount requested 0.00mBTC" in Payment Details 

![screenshot_20180123-123602](https://user-images.githubusercontent.com/35691462/35273929-90ac7254-003a-11e8-84ca-7748e2552aa3.jpg)

**Comment by AndWav** [comment]
Sorry, it was *msastoshi* according to cli/lightning-cli listinvoices :
{ "label" : "label0014", "payment_hash" : "81b78b0884b9e6399d46f        3dd04c6901d719878743ad5f5e1cc8af96d13533b68", "msatoshi" : 500, "status" : "paid        ", "pay_index" : 4, "msatoshi_received" : 500, "paid_timestamp" : 1516707372, "p        aid_at" : 1516707372, "expiry_time" : 1516710852, "expires_at" : 1516710852 } ]         }

**Comment by dpad85** [comment]
This is a display issue. The amount is correctly understood by the underlying node and - as you see in the invoice - the htlc sent is correct.

Milli-satoshi should be used for internal calculations only, this is why the UI in eclair wallet rounds the sub-satoshi part. However, it is possible to generate a payment request with a milli-satoshi part. So in the UI `500 msat = 0.5 sat` becomes `0 sat` and this is a bad user experience because what you see is not what you send.

**Comment by dpad85** [comment]
The fix for this issue will be available in the next release (0.2.4).

**Comment by dpad85** [comment]
0.2.4 is now available and fixes this issue.
