### ISSUE TITLE
No route found when sending funds from android to PC

### ISSUE THREAD

**Issue by dot3bumpmap** [ACINQ/eclair#411]
I have setup Eclair Win64 node and opened a couple of channels, including a channel to 
03c4b20397d476a0d008e61022c96803ada3c11918fff8133db4f7d27273710e03 (pikefloyd)
which I have found through https://explorer.acinq.co/#/ and it seems like it is rather well-connected

I also have the Eclair android app which has an open channel to pikefloyd too. I'm able to buy coffee on starblocks.acinq.co from both my android phone and windows eclair wallet, however when I try to send BTC from my android phone to my windows eclair wallet payment fails. Error screen shows numerous attempts. First one is "NoRouteFound" and others are "TemporaryChannelFailure". I have experimented with various amounts(including very small) but no luck

Is this a bug or I'm missing something ?

**Comment by pm47** [comment]
Eclair did find some routes and tried them all, but none of them worked out so it concludes with an arguably misleading "route not found" error.

Temporary channel failures occur when the channel you want to pay through cannot *currently* relay your payment, most probably because it is unbalanced. You cannot send to a channel if you don't have funds on your side of the channel.

In your case, since you have opened a channel to pikefloyd from both your mobile phone and your desktop computer, all funds must still be on your sides of each channel. Pikefloyd can't send anything to your desktop because all funds are on your side. Try using the `push_msat` feature to create a channel from your desktop to pikefloyd with an initial amount on their side (like half the amount).

In the end I see no bug here. Dual funding (scheduled for LN 1.1) will make it possible to create balanced channel, which will help a lot for cases like this.
