### ISSUE TITLE
Transaction wan't broadcast from android wallet - epic confusion ensues.

### ISSUE THREAD

**Issue by lambohunter** [ACINQ/eclair#413]
Using Android wallet...

Transaction ID: f5a84164895d418fe6a76a86224b046c855b92fc00fefff26ed31fdcb4c03e08

1. Attempted to open a channel. ![funding](https://user-images.githubusercontent.com/35875901/35475727-fec0d87a-035f-11e8-9ce3-6530c784f30a.png)
2. Funding transaction never got broadcast.
3. Stuck with waiting for confirmation for days.
4. Tried to close channel. 
![closing](https://user-images.githubusercontent.com/35875901/35475728-0e587306-0360-11e8-9049-48700556feb8.png)

5. Cannot close channel because funding transaction was never broadcast.

Might also be helpful to allow in app reporting of errors.

**Comment by pm47** [comment]
Expiration of funding tx is not implemented yet, and there is actually still discussion on the mailing list on the best way to handle that kind of things. Granted this is a major UI annoyance.

On top of that, it seems you really got stuck in a corner case: the electrum server you were connected to did acknowledge the publication of the funding tx (otherwise your channel would be in state `ERR_FUNDING_PUBLISH_FAILED`). I wonder how specific to testnet this particular behavior would be.

Do you see the funding transaction in your tx history (default screen) with 0 conf? If so, can you click on it and try to rebroadcast it?

**Comment by dpad85** [comment]
Moved this issue to the eclair-wallet repo.
