### ISSUE TITLE
Stuck with the same OFFLINE / CLOSING node, all payments fail

### ISSUE THREAD

**Issue by Stadicus** [ACINQ/eclair#415]
Running Eclair alpha9 on Linux, I have 6 channels open. Status: 4 OPEN / 2 OFFLINE. When sending to Y'alls,  I always get the API answer (at least using cURL, see issue #414 )

    The server was not able to produce a timely response to your request.
    Please try again in a short while!

Eclair always tries to send the funds through one of the OFFLINE nodes. Even after closing the channel, with the node status CLOSING, the same node is selected and the payment always fails.

![eclair 2 - connect to offline peer](https://user-images.githubusercontent.com/19550140/35476184-1d36b6f2-03ac-11e8-8bd2-afd440349ed1.png)

See combined command line / logfile entries in Pastebin:
https://pastebin.com/LSBzshj8

I also get a lot of these error messages in the log (see #409 )

    requirement failed: invalid macjava.lang.IllegalArgumentException: requirement failed: invalid mac

**Comment by pm47** [comment]
Here is what I think is going on:
1) you have recently restarted eclair to upgrade from alpha8 to alpha9
2) eclair is busy re-validating all channels (it shouldn't have to do that since they were already validated when eclair received them the first time, but that's how it's done now; we are working on this)
3) your sending request is waiting for the routing table validation to finish, which causes it to timeout. it will be sent eventually, but the API call will have timed out in the mean time.

What you are seeing in the logs are just reconnection attempts to nodes that are currently OFFLINE, they are unrelated to sending payments.

What happens when you grep your logs for the string `validation`?

**Comment by Stadicus** [comment]
Yes, I updated the system last Tuesday evening, 4 days ago. I think it was running most of the time. However, I deleted the log once. 

Please find the current log (dating back to yesterday) in Pastebin. There are 1100+ lines containing `validation`
https://pastebin.com/nU5TCmZK

**Comment by pm47** [comment]
Ok, if you haven't sent the payment requests right after having restarted eclair, then my theory is wrong. The logs you have uploaded show that upon startup eclair goes through re-validating all nodes correctly, I see nothing abnormal.

Can you reproduce this at will? If so, a full log starting when you send the API request could help.

Thanks!

**Comment by Stadicus** [comment]
I just restarted the eclair service with a new logfile. Please find the log including my commands (with some timestamps) attached.

[Eclair_415_commands.txt](https://github.com/ACINQ/eclair/files/1671256/Eclair_415_commands.txt)
[eclair.log](https://github.com/ACINQ/eclair/files/1671258/eclair.log)

The errors for commands "send" (to Starblocks) and "allnodes" persist.

**Comment by pm47** [comment]
By restarting eclair you put yourself in the case I was describing above: eclair is busy validating the routing table and can't handle your requests in time (*).

Sorry for the misunderstanding. What would be interesting is see what happens if you submit those requests when eclair has finished validating all the channels (when you stop seeing "validating a batch of 50 channels"). If your requests still timeout then we might have a bug.

(*) eclair is built around the actor model. Actor are lightweight processes that react to messages sent to their mailbox. They basically just loop and process messages one by one. The `router` is an actor in charge of building the table, finding routes, listing all the nodes, etc. What happens here is the actor's mailbox is filled with channel validation requests, and your requests are queued. The API will only wait for so much before giving up and timing out, but it doestn't mean that the request won't actually be processed afterwards. You may wonder why we don't parallelize, but we can't because we actually want the routing table to be correct before trying to send payments. The only issue here is that the whole re-validation of channels is completely superfluous and should be skipped.

**Comment by Stadicus** [comment]
Well, that was not that smart of me... :-) I'll get back to you, once the repeated validation stops. 

It occurs to me that this process takes veeeery long... see `grep validat eclair.log`
https://pastebin.com/ky59CzWT

**Comment by pm47** [comment]
If you feel like trying bleeding edge tech, you can build #421, announcements won't be re-validated at startup.

**Comment by zanderisrael** [comment]
Same here, looks like an issue for smaller devices like Rpi. 
The re-validation takes a very long time.

**Comment by gregtronel** [comment]
Same issue, running on RBP3.
