### ISSUE TITLE
eclair version alpha8 vs alpha9

### ISSUE THREAD

**Issue by curiosity81** [ACINQ/eclair#426]
After starting alpha9, the program told me that the new version is not backward compatible with alpha8 and that I have to clear my config-directory. So I deleted the logs firstly and started again. The same message popped up, then I deleted the sql-database and the GUI came up. Clearly I checked the Readme-Link but there was no information about handling this issue.

**Now all my channels are gone and all the used tBTC ended up in the testnet limbo, there is no transaction back to my wallet with the corresponding coins.**

**This must be solved! It cannot be that a new version removes all channels and "destroys" the used coins. The channel information must be kept, even when the database structure is altered.**

**In such cases there must be a function reading in the old database and then construct the new database! Or alternatively, all the channels should be closed before removing the data from the config-directory.**

Then, how do I remove my node from the network? Even though I do not have the information about my channels, the network explorer still shows old channels. So obviously, someone still has channels open to a zombie node or are itself zombie nodes.

**I think it is essential, that nodes which are NOT running in the moment are shown correspondingly in the network explorer! The network gives no information about real, that is, running nodes and marks zombie nodes.**

Also it takes quite long until the IP is correctly shown. In the moment it is not shown correctly yet.

**Comment by curiosity81** [comment]
BTW, it would be nice to have a way to search in the different tabs of the GUI. Especially in the "All Channels"-tab. A simple string search would be nice which restricts the shown data frame/matrix to the rows where the searched string is found in.

**Comment by verretor** [comment]
I think the main difference was eclair.conf (JSON API password). I use the same nodes as before alpha9. The only differences I put in eclair.conf:
```
eclair.api.enabled=true
eclair.api.password=hunter2
```

Also, by default, the JSON API is disabled.

**Comment by sstone** [comment]
Release notes for alpha9 clearly state that "This release includes a breaking change in local database format, please close all channels before updating". We could add this to the warning displayed in the GUI. Your concerns are valid but handling breaking changes is not always easy and adds constraints that we could do without right now, asking users to close their channels is the simplest option. Of course we have proper ugrade tools before we release eclair for mainnet.
Since a channel that you've opened with a node that is never online is useless but locks some of your money, they will end up being closed and they will eventually be pruned from the network view. Nodes will be pruned too when there are no longer any channels attached to it. But this is node-specific and has not been completely implemented, and testnet has different incentives (there is no real money at stake). 
It takes 6 additionnal confirmations for a channel to be announced once it's been opened, on testnet it may take a long time (block intervals are quite unpredictable on testnet).

**Comment by pm47** [comment]
> This must be solved!

 No it doesn't: keeping the ability to break backward compatibility is the reason why we are still alpha and allows us to go faster. This is also why we urge people not to run anything on mainnet.

> Then, how do I remove my node from the network? [...] I think it is essential, that nodes which are NOT running in the moment are shown correspondingly in the network explorer!

You don't have to do anything, channels and nodes get pruned after 2 weeks as specified by BOLT 7.
