### ISSUE TITLE
Sending the same payment request twice fails? 

### ISSUE THREAD

**Issue by dinnerisserved** [ACINQ/eclair#46]
Sending a payment to the same payment request, more than once fails? Is this intentional or a measure to prevent mistakes? 

In case this is intentional due to that the request is uniquely tracking the preimage secret, would it be possible to create payment requests that are user friendly as a layer on top of it?

**Comment by pm47** [comment]
> Sending a payment to the same payment request, more than once fails? Is this intentional or a measure to prevent mistakes?

It is intentional, the payer must explicitely create a new request for each payment, [BOLT 4](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#failure-messages) even defines specific error codes for `unknown_payment_hash` and `incorrect_payment_amount`.

> In case this is intentional due to that the request is uniquely tracking the preimage secret, would it be possible to create payment requests that are user friendly as a layer on top of it?

Indeed, if you send the same payment twice, chances are that it will use part or all of the same route than previously, and an evil node on the path will be able to pull funds from upstream without sending funds to downstream.

Note that the format of payment requests hasn't been specified yet, and our implementation uses an extremely simplistic one, which isn't even signed. It will definitely be standardized before LN goes live, but the request will still have to be generated by the receiving node, so any additional layer will have to be tied to that node.

**Comment by pm47** [comment]
I think I can close this?
