### ISSUE TITLE
encrypting the JSON-RPC API connection.

### ISSUE THREAD

**Issue by AndySchroder** [ACINQ/eclair#476]
The JSON-RPC API connection is password protected but not encrypted. Is there any intent to add https support? If not, what is the recommended approach to secure the JSON-RPC API? stunnel, ssh tunnel, VPN, something else, any of the above?

**Comment by pm47** [comment]
> The JSON-RPC API connection is password protected but not encrypted. Is there any intent to add https support?

We don't intend to add support for https in the short term, and we want to be clear that this API should not be exposed over the internet (just like the Bitcoin API when wallet is enabled).

> If not, what is the recommended approach to secure the JSON-RPC API? stunnel, ssh tunnel, VPN, something else, any of the above?

Normally I would suggest using a local ssl proxy (e.g. with nginx), but since the API isn't designed to be exposed to the outside world (even with a password), best option is to use a ssh tunnel since it means  client authentication by default.

**Comment by AndySchroder** [comment]
Okay, thanks for clarification. It's understood that you may not want to deal with natively securing this properly right now.
