### ISSUE TITLE
Force close channel state in 'CLOSING' for long time

### ISSUE THREAD

**Issue by nm123github** [ACINQ/eclair#510]
- Created a channel with a node
- Bought some coffee on https://starblocks.acinq.co/#/
- Force closed the channel

I was expecting the balance of the channel to come back to my wallet but don't see it. Is that a correct expectation for above use case?
![image](https://user-images.githubusercontent.com/8527474/37868592-5ddd00f4-2f66-11e8-9523-13a579002614.png)

**Comment by pm47** [comment]
Hi, can you copy paste the `Funding tx id`?

**Comment by pm47** [comment]
Ok, got the [funding tx](https://api.blockcypher.com/v1/btc/test3/txs/6ccde0661b71097302fbaa70f2514ed58dde157ca780d3a969bb56595d9e13de) from the screenshot.

It has indeed been spent by your [commitment tx](https://api.blockcypher.com/v1/btc/test3/txs/20bef746514998a80e1257f952cd6cc86c462634abd2e5fa37052fa982229bbd), which currently has 66 confirmations. When it reaches 144 confirmations, you'll be able to spend it and you will see an incoming tx back to your wallet. If you had done a mutual close instead of a force close, the refund would have been instant.

I see no bug here and am therefore closing the ticket, please reopen if necessary.

**Comment by pm47** [comment]
Note: when the (not yet published) transaction sending funds back to your wallet reaches 2 confirmations, then state will switch to `CLOSED`.

**Comment by nm123github** [comment]
Thank you 👍
