### ISSUE TITLE
"Expiry too small" error

### ISSUE THREAD

**Issue by kilimanjarolows** [ACINQ/eclair#526]
Eclair yields the following error:

> expiry too small: minimum=1289632. Actual=1289630. BlockCount=1289623

What does this error means?

The error happens when making a payment to a lightning node I run myself. The lightning node uses lightningd. A channel with the node is established successfully. A payment to the node was done successfully using another lightningd node (and another channel).

**Comment by sstone** [comment]
It means that the delay after which this payment will time out and can be claimed back by the sender is too short (here it is 1289630, expressed in blocks, i.e in 7 blocks since we're at 1289623). 
Eclair expects payment expiries to be strictly more than 7 blocks in the future, and the LN specifications defaults in BOLT11 is 9 blocks . 
Since it is a lightningd node that you run yourself, if you start it with a larger final payment expiry (for example `--cltv-final=10`) your payments should work.

**Comment by dimitris-t** [comment]
Hi, I am getting the same error when paying a request by c-lightning (using a default configuration):

> 1 attempts: - (local) expiry too small: minimum=1289718 actual=1289717 blockCount=1289711

The payment request is:
> lntb10n1pdt6y70pp5wtp6j637wzpy2xh7tyf0fxsms5nvm52mlcnrj8splfssp0hzvf4sdq0v35k66t5wf5hxvscqpx3ypd25r55q0368f0p52670t9ypwkf7t0dwngekxega6r8z7wj87x29w5kgc2e6gzc0jyxkv4w97qzspv9aq2ce67krt6q48uq5fgkycqs0930h

Should the receiving party issue a new payment request with a larger final payment expiry?

What does this tell us about compatibility between different Lightning implementations?

**Comment by sstone** [comment]
Same reason: your payment request includes a `min_final_cltv_expiry` tag of 6 blocks, issuing a new payment request with a `min_final_cltv_expiry` of at least 9 blocks should work. 

As for compatibility issues, it means that default configurations still need to be adjusted, and it this case I believe that clightning's default value is too low (but simple enough to change)

**Comment by verretor** [comment]
I tried to have cltv_final increased in c-lightning (see pull request above). I doubt they will merge it.

**Comment by cdecker** [comment]
@verretor I'm reconsidering the PR, I'd like have at least compatible default value.

@sstone I'm still not sure why eclair would enforce the final CLTV delta of 10 on the last hop for sending payments, even though we explicitly signaled that we're happy with 6. This is really confusing to me, since your path finding code will happily produce such a route, but then when issuing the payment using that route, the routing mechanism refuses to route it. I think rather than us having to bump the default param, Eclair's path finding should be amended to bump the CLTV delta if it's too small, since we will accept something that is higher than our default.

I remember we talked about this before, and I think I convinced you that Eclair was enforcing a value that it should not, and even if, it should be the sending side to ensure its lower bounds are met. Why should we as receiving party have to guess what the sending party's implementation is so that we can pass them an invoice that matches their enforced values?
