### ISSUE TITLE
Can't open a channel, entry disappears after "WAIT_FOR_ACCEPT_CHANNEL"

### ISSUE THREAD

**Issue by kilimanjarolows** [ACINQ/eclair#536]
I open a channel to a certain node from the app. The status hangs on 'WAIT_FOR_ACCEPT_CHANNEL' for about a minute, then the entry disappears.

I installed the Eclair wallet today from Google Play store.

I manage to open a channel to this node from lightningd on my computer. The lightningd version on both ends is: v0.5.2-2016-11-21-2451-g26f7014

I understand that it may be a duplicate of https://github.com/ACINQ/eclair/issues/437. But https://github.com/ACINQ/eclair/issues/437 was supposedly fixed in https://github.com/ACINQ/eclair/pull/453. Is it included in what I downloaded from the Play store today?

**Comment by pm47** [comment]
This is indeed adressed by #453, but note that:
- this pull request has _not yet_ been merged into master
- our node endurance.acinq.co (which is where autoconnect points to) already has #453, so you can try it out
- issue is more on the remote peer side than on your side, so #453 won't even solve it: what you want is that your lightningd supports advanced routing sync. Good news is: they are working on it!

**Comment by pm47** [comment]
The issue is that when you connect to your node, it sends the whole routing table (instead of the diff with the new feature), which is quite a lot of routing messages, causing your channel-related messages to be delayed. But eventually they should go through, so if you just wait the channel should be created.

The catch is that before reaching state `WAIT_FOR_CONFIRMED`, eclair wallet won't remember the channel (which is the correct thing to do), so you need to leave your app open. Also, every time you will restart the app, the same sync will happen again, so even if you manage to open a channel, you will still experience lag when trying to send payments.

**Comment by kilimanjarolows** [comment]
Thanks. It works great with endurance.acinq.co.

I didn't manage to get it to work without (maybe I don't wait enough), but I'm closing the topic anyway.
