### ISSUE TITLE
Invalid commitment sig received from LND

### ISSUE THREAD

**Issue by pm47** [ACINQ/eclair#575]
Hi @alexbosworth, have you done anything special on yalls node `03e504` today? Both channels open to it have failed. Do you happen to have logs for channel `8c735210f593406af4146e3f7bbc7e118d3e839075dfe47f23c93e0344987ec3` ? Thanks!

[8c735210f593406af4146e3f7bbc7e118d3e839075dfe47f23c93e0344987ec3_lnd_invalidsig.log](https://github.com/ACINQ/eclair/files/1943709/8c735210f593406af4146e3f7bbc7e118d3e839075dfe47f23c93e0344987ec3_lnd_invalidsig.log)

**Comment by alexbosworth** [comment]
I haven't done anything recently -
It's currently running LND `0.4.1-beta commit=8af80bfc5cdebcd323ed2a50ea0497df6e9bc6e4`

I don't see anything in the logs that seems strange but I'm not logging at a high level atm

**Comment by Roasbeef** [comment]
Nothing forwarding or channel update related has had its logging verbosity reduced recently. The only thing that has is processing gossip related network messages.

**Comment by BitBargain** [comment]
Please see the logs over at https://github.com/lightningnetwork/lnd/issues/1161

My issue is invalid-commitment-from-eclair-to-lnd, the reverse of this one but I figured the fix is likely the same to both problems. So I hope the logs from the LND side can help to track this down.

Another piece of info which may or may not help: the person who's experiencing this issue is using the same LND node as me, they're using the same Eclair as me, yet it constantly fails for them and works 100% of the time for me.

**Comment by pm47** [comment]
This is old and may have been fixed in more recent releases of `lnd`. Let's close this and reopen a new issue if issue surfaces again.
