### ISSUE TITLE
Router TickPruneStaleChannels taking 3-4 mins and pruning channels many times?

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#624]
Concerned that this actor is blocked for this long. e.g RouteRequests are blocked.
Is taking this long every hour. Might be because I am running node with db on an Amazon NFS drive so I can recover.
```
21:57:14.052 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - pruning shortChannelId=7e8280004040000 (stale)
...
22:00:52.826 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - pruning nodeId=0321b23e7c8eabbee13fbd9abca31f2e32a691bccde3530c1f081f4c488ab66ed6 (stale)
```
Also we seem to prune nodes/channels many times. Looking in my log for today we pruned 17k nodes+channels! There were 2600 unique items pruned but many had been pruned 6-7 times??

Taking one example I see:
```
00:27:33.438 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - pruning shortChannelId=7f1ad0002ec0001 (stale)
12:46:00.130 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - validating shortChannelId=7f1ad0002ec0001
12:46:09.606 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - got validation result for shortChannelId=7f1ad0002ec0001 (awaiting=18 stash.nodes=0 stash.updates=10)
13:27:40.249 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - pruning shortChannelId=7f1ad0002ec0001 (stale)
14:35:51.529 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - validating shortChannelId=7f1ad0002ec0001
14:36:07.038 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - got validation result for shortChannelId=7f1ad0002ec0001 (awaiting=254 stash.nodes=0 stash.updates=1)
15:26:31.763 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - pruning shortChannelId=7f1ad0002ec0001 (stale)
16:07:15.729 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - validating shortChannelId=7f1ad0002ec0001
16:07:37.691 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - got validation result for shortChannelId=7f1ad0002ec0001 (awaiting=254 stash.nodes=0 stash.updates=1)
16:58:22.806 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - pruning shortChannelId=7f1ad0002ec0001 (stale)
17:56:07.043 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - validating shortChannelId=7f1ad0002ec0001
17:56:07.274 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - got validation result for shortChannelId=7f1ad0002ec0001 (awaiting=2 stash.nodes=0 stash.updates=0)
17:58:07.488 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - pruning shortChannelId=7f1ad0002ec0001 (stale)
18:15:05.080 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - validating shortChannelId=7f1ad0002ec0001
18:15:05.198 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - got validation result for shortChannelId=7f1ad0002ec0001 (awaiting=3 stash.nodes=0 stash.updates=2)
18:58:22.036 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - pruning shortChannelId=7f1ad0002ec0001 (stale)
21:02:18.413 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - validating shortChannelId=7f1ad0002ec0001
21:02:53.101 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - got validation result for shortChannelId=7f1ad0002ec0001 (awaiting=130 stash.nodes=0 stash.updates=0)
21:58:04.541 INFO  akka://default/user/$f/router fr.acinq.eclair.router.Router - pruning shortChannelId=7f1ad0002ec0001 (stale)
```

So actual issue seems to be we are adding/removing channels we should not be?
Was thinking of updating to run the purge more often. But that looks like it would make issue worse!

Has a valid unspent funding tx: e387eeb4686bc3424ba7d1e7345bf827619e07fd07ef0f7c29110913a0e06c59
from 30th April. So over the 2 weeks old. But guess there are not channel update but someone keeps republishing the channel announcements?

Today I only purged 65 channels once. So real purges. But 2108 channels are in the state above am I purged them 5-7 times!

**Comment by pm47** [comment]
This is called the "zombie churn", is well known since the testnet deployment and is not specific to eclair.

> But guess there are not channel update but someone keeps republishing the channel announcements?

Exactly. It seems some nodes are still sending stale channels, [despite the recommendations in the spec (BOLT 7)](https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#pruning-the-network-view).

Thing is, validating a channel is two-fold: (1) making sure that the `channel_announcement` is valid (which includes the expensive check that the related funding tx is valid) and (2) making sure that there is a recent enough `channel_update`.

Current strategy is:
1) we validate `channel_announcements` as they arrive
2) we record `channel_update` as they arrive if they are related to an existing channel and are recent enough
3) every hour we prune the whole routing table

We could try to be smarter, but it is not trivial and before getting to that, I'd rather wait for everyone to update their nodes, maybe even blacklist non compliant nodes. Let's keep in mind that current routing table sync is extremely simple, other implementations are just about to merge the diff-based "advanced routing" mechanism.

**Comment by n1bor** [comment]
Shall I upload a pull where we just keep a list of all channels we have purged in the last 7 days (and delete from that list if we get an channel_update). And just ignore any announcements from them?
At the end of the day we need a practical solution - and there are always going to be people with bad nodes.

**Comment by pm47** [comment]
> Shall I upload a pull where we just keep a list of all channels we have purged in the last 7 days (and delete from that list if we get an channel_update)

It's not as easy as it seems, because `channel_update`s are always sent *after* `channel_announcement`s, so you still need to remember them and that could be a vulnerability. But actually we could indeed do what you propose, except that when we receive a `channel_update`, we clean the banlist and then request this specific channel using a `query_short_channel_ids` query, which would cause the node to send again the `channel_announcement` and `channel_update`s. This query is part of the "advanced routing sync" feature that isn't yet merged in the specs -- but will soon.

> At the end of the day we need a practical solution - and there are always going to be people with bad nodes.

Sure. To be clear we are still at the pre-optimization phase, and there are plenty of low hanging fruits. Re: bad nodes, I mentioned blacklisting which is still to be implemented.
