### ISSUE TITLE
Expired payment not being failed by Endurance

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#649]
I have two outgoing payments sent from `phone -> endurance -> ... -> lncast` which are expired by now but they are not being failed by `endurance`. My wallet should have closed a channel by now but I use a custom version which does not do that specifically to detect such cases.

Local peer id: `03cb7c2acef2d1509b12ad3d216036356a4947311c1c67237a50de64527fb66da8`
Remote peer id: `03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134`
Channel id: `2a2bd2255cad190ea80dde18cff1f384a14042ce4477c33850966f660f90b933`

Stuck payments hashes:
`216e58d46f264ec4ee1ad415dbb6b8fed6c0bcb1646bcfb205dff205d67f2436`
`1bb4f552c88642ed11b45813809708ae90d2634ad492639fb0c3f15d070cd512`

**Comment by pm47** [comment]
Good catch! Here is what happened:

```
             03cb7c           039338           03dc39
		|              |  |              |
		|--- add-18 -->|  |              |
		|---- sig ---->|  |              |
		|<--- rev -----|  |              |
		|<--- sig -----|  |              |
		|---- rev ---->|  |              |
		|              |  |--- add-29 -->|
		|              |  |---- sig ---->|
		|              |  |<--- error ---| expiry too big! (5326 blocks ~ 36 days)
		|              |  |              | 039338 publishes its commit tx (no htlc)
		|              |  |              | channel closed
```

Downstream node `03dc39` rejected the htlc because the expiry is huge (NB: not sure why the htlc wasn't rejected by endurance (`039338`) for the same reason, maybe there was a big reorg exactly at that time?).

Endurance published its local commitment tx, which doesn't contain the htlc, it "won" the race against the commitment from `03dc39` (which contained the htlc), got confirmed and reached `min_depth`. Current code only fails htlc that hare in the commitment tx that got confirmed (NB: we do check `localCommit`/`remoteCommit`/`nextRemoteCommit`, but as soon as the commit tx reached `min_depth` we cleaned up the channel and stopped caring about it):

https://github.com/ACINQ/eclair/blob/923d8661f85249ec24c4ddaef404338756dcc09c/eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala#L1166-L1176

=> When we consider a channel closed, we must fail all known upstream incoming htlcs, not only the ones that were included in the commitment that was confirmed.

**Comment by pm47** [comment]
@btcontract 2cec8cce10e2b192340c2e7ed086cdd7493e68e3 should fix the issue

**Comment by btcontract** [comment]
Is this fix already on testnet? I have another 130 SAT payment which got stuck today with Endurance.
