### ISSUE TITLE
Dijkstra may fail to find a shortest path with negative fees present

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#668]
I haven't tested this yet but it appears that a Dijkstra also has a requirement for all edge weights to be non-negative while negative routing fees are allowed in LN. This may result in something like https://stackoverflow.com/questions/6799172/negative-weights-using-dijkstras-algorithm/6799344#6799344

One quick fix could be `def nodeFee(baseMsat: Long, proportional: Long, msat: Long): Long = math.max(0, baseMsat + (proportional * msat) / 1000000)`, another would be to replace Dijkstra with Bellman-Ford, the tradeoffs are described here: https://stackoverflow.com/a/19482341/179746

**Comment by btcontract** [comment]
after some additional conversations negative fees seem like a bad idea anyway when explicit rebalance could be used to achieve similar results so perhaps `def nodeFee(baseMsat: Long, proportional: Long, msat: Long): Long = math.max(0, baseMsat + (proportional * msat) / 1000000)` is the best solution.

**Comment by sstone** [comment]
LN routing fees cannot be negative ("All data fields are unsigned big-endian unless otherwise specified."). 
Negative relay fees were considered at the beginning, to create incentive for channel re-balancing, but quickly dropped (see https://lists.linuxfoundation.org/pipermail/lightning-dev/2017-December/000827.html and https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-January/000938.html).
