### ISSUE TITLE
Provide more details in the channels API

### ISSUE THREAD

**Issue by gustavonalle** [ACINQ/eclair#677]
The ```channels``` command displays ```nodeId```, ```channelId``` and ```state``` for each channel. Some basic stats specially related to balances (local and remote) would be appreciated

**Comment by d4amenace** [comment]
I'm also wondering if it's possible to show capacities for receiving for a particular node since that's limited to how much that node has sent out and also capacities for connecting new channels so that you can avoid connecting to a channel that doesn't have the capacity to confirm the connection and cause Channel problems.

**Comment by gustavonalle** [comment]
cool, I am not seeing this. Maybe I need to update my code

**Comment by gustavonalle** [comment]
I was using an older version of eclair, now I can see the channel details
