### ISSUE TITLE
Eclair does not detect that bitcoind is reindexing and not ready yet

### ISSUE THREAD

**Issue by sstone** [ACINQ/eclair#737]
When eclair starts, it checks that it can connect to a Bitcoin Core node, and that this node is "ready" to be used (fully synced). But we don't detect that Bitcoin Core is reindexing which will interfere with our ability to detect that funding transactions are confirmed for example (see #734).

Reported by @Flekoun

**Comment by pshep** [comment]
Further to this, Eclair should continue to attempt RPC connections on start-up until told otherwise.
At the moment, on machine boot where Bitcoin Core and Eclair are started at the same time, Eclair fails to connect to Bitcoin simply because it started first.

**Comment by dscotese** [comment]
I agree.  It throws an error in several conditions that really only call for one or more of:

1. Getting the user to do something.
1. Waiting for something to get finished.

Instead of an error, eclair could create an information dialog that updates on what it's doing and a few troubleshooting tips - Waiting for RPC to come available ("Is your Bitcoin client started?") or waiting for indexing to be completed ("Are you connected to the Internet?").  This way the significant time spent during initialization could be skipped.  Right now, it seems the only choice is to close and then start eclair again once the conditions have been corrected.

**Comment by araspitzu** [comment]
Is this still an issue after #1138 ?

**Comment by sstone** [comment]
No , it seems that #1138 did fix it (no new reports here or on gitter).
