### ISSUE TITLE
Stuck outgoing payment with ACINQ peer

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#745]
A user reports two expired payments sent through ACINQ node, details are here: https://github.com/btcontract/lnwallet/issues/99#issuecomment-432511392

**Comment by pm47** [comment]
Just for reference, we are talking about:

payment_hash_1 = `ab7af8abdea15a4f42f44ba323f4daf19d6e7d658b6034c51021d036b5e040f3`
payment_hash_2 = `c225145655386c64e0241fab90b57b3f6392ae76f4183813c0daa8e312867a77`
channel_id = `712213ec4d572711c1778092333d057948331a2d4d6be65b140e6600da8f2458`

**Comment by pm47** [comment]
This is a mix of several issues:
- a sigcheck bug causing connection-wide errors between peers (fixed in #740)
- lnd currently ignores `error` messages while we are making the assumption that they will close channels when they receive them
- we should reset the connection to a peer that doesn't answer to `commit_sig` after e.g. 30 seconds. This would cause pending htlcs to get failed
- we don't handle well ctrl+c on eclair when there are pending unsigned htlcs; usually it is a small corner case, but this is aggravated by the points above. Note that #659 intends to fix that but it is still a work in progress
