### ISSUE TITLE
Eclair is running 24/7 but still barely available.

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#822]
My node seems to be mostly unavailable even though it is online 24/7

there are 3 reasons why I'm suspecting this:

1. I almost always get an error when trying to send a payment. I usually have to restart eclair before I can pay an invoice.

2. I don't have many channels but all are well funded and well balanced and my fees are pretty low. Still I only once ever relayed a payment in more than 4 months running the node non stop day and night.

3. The new Node Rank™ feature on 1ml.com shows a very bad availability ranking for my node. Much worse than other younger nodes.

Is there any way to figure out what the issue is?

**Comment by araspitzu** [comment]
Please consider that the 'availability' is a slightly subjective measure (might be due to the *ping/pong* response time), and even if your node is _very available_ it's not guaranteed that will route payments, actually there might not be payments to route at all. You probably want to make sure you are connected to central nodes and that your channels make a route cheaper for someone else (so that you'll be selected by their route finding mechanism) and 'fees are pretty low' must be measured against what other channels are offering at the moment, keep in mind channel fees can change at any moment.

**Comment by viaj3ro** [comment]
>You probably want to make sure you are connected to central nodes and that your channels make a route cheaper for someone else (so that you'll be selected by their route finding mechanism) and 'fees are pretty low' must be measured against what other channels are offering at the moment, keep in mind channel fees can change at any moment.

you just perfectly described my Node ;) that's why I'd expect to at least relay more than once in more than 4 months.

also point one! whats up with this one? Why do I have to restart every time I actually wanna use my node?

**Comment by araspitzu** [comment]
Staying on top of the routing is hard and very demanding because the network topology is constantly changing and if you want to be the 'cheapest' you'll need to follow closely and adapt, also some clients are now using heuristics to select the routes so having lower fees might not be enough to end up relaying payments. Point 1? Please provide the errors you get before restarting (but maybe on issue #823 ?)

**Comment by viaj3ro** [comment]
I understand that. Alex Bosworth explained it very well: https://www.youtube.com/watch?v=HlPIB6jt6ww

It's more like the combination of all the points made me skeptical.

regarding point 1, it used to be mostly issue #758 - I don't get it anymore though. Lately it has been this:
2 attempts:
- (remote) payment expiry is too close to the current block height for safe handling by the relaying node
- (remote) payment expiry is too close to the current block height for safe handling by the final node

unfortunately I don't have the logs for this one handy and can't really replicate it at the moment due to my issue #823 but in both cases a node restart helped to mitigate the error.

**Comment by araspitzu** [comment]
Availability can also be measured as how promptly your node can respond to the ping and/or how much 'flapping' do your channels do (flapping as in enabling and disabling the channel mostly due to transport errors). If you want to improve on the availability side i would recommend to carefully measure how long your open channels stay in states != NORMAL, it may happen for various reasons that eclair closes a connection to a non responsive peer, then if you had a channel with that peer it's going to be unavailable and that's probably bad for your node _availability ranking_ .

**Comment by viaj3ro** [comment]
I only maintain channels to reliable 24/7 nodes. It almost never happens that a channel state is anything but normal.

Just received this eMial today. Another confirmation that something is wrong with my node:

> Hi
> I cannot connect to your node.
> [lncli] rpc error: code = Unknown desc = dial tcp 31.16.118.221:9735: connect: connection timed out
> It seems to be offline.

Can you connect to my node?

**Comment by viaj3ro** [comment]
Even with the latest beta 9 people can't reach my node. Hopefully somebody here has any ideas how to fix my issue...

> I tried to set up a channel, but still cannot connect to your node.

> lncli connect 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.118.221:9735

> [lncli] rpc error: code = Unknown desc = dial tcp 31.16.118.221:9735: connect: connection timed out

**Comment by araspitzu** [comment]
Your node (@ 31.16.118.221:9735) is not reachable from the internet. If you're running on a LAN make sure the router has port forwarding enabled and it will forward traffic going into the 9735 to your eclair host.

**Comment by araspitzu** [comment]
Positive! Connection was successful to your node, hooray!!

**Comment by viaj3ro** [comment]
still doesn't explain why I have to restart my node pretty much every time to actually be able to use it. Requested a couple payouts from a peer just now and only got them through after a restart. Sending even small 1-5k sats payments looks mostly like this: https://imgur.com/a/yMMXi4r

Since beta 9 most of the labels (node aliases) are missing, btw.

Anyway, don't wanna waste anyones time. Just let me know, if there is anything I can do to help improve things. Wasn't my intention to come here just to complain ;)
