### ISSUE TITLE
Opened a new channel and now eclair ignores all the other channels when I try to make a payment

### ISSUE THREAD

**Issue by viaj3ro** [ACINQ/eclair#823]
After opening a well funded channel to the blockstream store LN node I suddenly can't make payments anymore through any of my other channels.

When I try to make a payment to bitrefill my node will attempt the payment via the channel to blockstream and usually fail after 5 attempts even though I have a direct and well funded channel to bitrefill. The same happens when I try to pay an invoice from lightningslotmachine.com - I do have a direct channel to them as well but eclair refuses to use it. it only sends via blockstream and is only successful for amounts up to ~1$ everything higher fails due to various reasons:

5 attempts:
- (remote) processing node does not know the next peer in the route
- (remote) channel 87fd30004d40000 is currently unavailable
- (remote) channel 87e980004eb0000 is currently unavailable
- (remote) channel 876c60007e10001 is currently unavailable
- (remote) processing node does not know the next peer in the route

here are the logs: https://pastebin.com/s1ZU0pCT

**Comment by araspitzu** [comment]
Can you specify what version of eclair are you running? Is `02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844` your node id? I've looked in the logs and there might be a problem with the retry of routes (and channel exclusion if an attempt failed)

**Comment by araspitzu** [comment]
The retry mechanism looks okay so it might just be an unfortunate case of failing nodes along the route(s) that your node tried.I noted that your channel with blockstream (WRONGSPAWN?) has much lower fees than your other channels (0.1 sat base fee) and thus it might be the case that the cheapest routes computed were *all* going through that channel. Note that this is still wrong because you actually had a direct channel with bitrefill and you should not pay fees at all! This behavior has already been 'fixed' in the master branch of eclair but no new beta release at the moment (means if you  want this fix you'll have to build eclair on your machine).

**Comment by viaj3ro** [comment]
yeah, that channel has lower fees but I have another well funded channel to LNBIG with the exact same low fees and it still only tries the channel to blockstream. At the very least it should try that channel as well. So it seems even with the fix you mentioned I'd still have the same problem in cases where I don't have a direct channel. It also means I can't have channels with different fee levels without effectively reducing my multi channel node to a single channel node?!

The algorithm should automatically choose different channels even with higher fees once routing via the cheapest channel fails.

I use the latest eclair release (0.2 beta 8)

**Comment by araspitzu** [comment]
Is not actually an error but the path finding optimizing for the cheapest route and it found that all of them pass through that node - if it had selected LNBIG probably the routes going through it were more expensive. Now in practice this calculation is wrong because the best route is actually the direct one. Stay tuned for the upcoming release that should fix this issue by selecting the direct channel (and later on you'll be able to prioritize more reliable channels over more expensive ones)

**Comment by viaj3ro** [comment]
Can I change the fees without closing the channel? Otherwise it seems my only work around would be to close the blockstream channel. By now I cant even get very low satoshi amounts through anymore... Kinda weird that this node is so bad at routing. I'd expect it to be one of the best nodes on the network?!

**Comment by araspitzu** [comment]
Yes you can change the fees with the API call 'updaterelayfee' https://github.com/ACINQ/eclair#json-rpc-api , this will create a new channel_update and let the network know the new fee parameters on a certain channel
