### ISSUE TITLE
Possibility of keyIndex duplicates

### ISSUE THREAD

**Issue by btcontract** [ACINQ/eclair#87]
If I'm not mistaken, does not picking a `keyIndex` the way it's done here: https://github.com/ACINQ/eclair/blob/master/eclair-node/src/main/scala/fr/acinq/eclair/io/Peer.scala#L276 may result in a duplicate value for different channels, especially for a busy node which would be opening a lot of channels, thus allowing peer to know sha preimages in advance and spend a favorable commit?  

Would not it be safer to use a unix timestamp for example?

**Comment by pm47** [comment]
Indeed this is a known issue and there is a TODO on this.

Note that knowing the sha preimages do not allow a peer to spend a commitment tx. It allows them to _steal_ the counterparty's outputs when they attempt an unilateral close. Of course that is still a bad thing.

Using a unix timestamp would probably not be safer, and wouldn't be deterministic, which is what we are trying to achieve here (otherwise we would just pick a random seed). What we intend to do is use a monotonic counter, it just hasn't been implemented yet.

**Comment by btcontract** [comment]
> Note that knowing the sha preimages do not allow a peer to spend a commitment tx. It allows them to steal the counterparty's outputs when they attempt an unilateral close.

Yes, sorry for vague formulations, this LN thing really goes hard with me :)  

> Using a unix timestamp would probably not be safer  

Since I currently try to build an LN wallet based on your code, what would your suggestions be for something safe and deterministic? (also why deterministic, is it so we can restore data later in case of loss?)

**Comment by pm47** [comment]
> Since I currently try to build an LN wallet based on your code, what would your suggestions be for something safe and deterministic? 

Just use a simple counter

> (also why deterministic, is it so we can restore data later in case of loss?)

That way we only need to remember the seed to retrieve funds in case of data loss (as long as there is no adversarial counterparty).

**Comment by btcontract** [comment]
Thanks!
