### ISSUE TITLE
maxValueInFlight error when opening new channel

### ISSUE THREAD

**Issue by kravens** [ACINQ/eclair#871]
Issue with opening a channel to LND / Zap node, error is unclear to us as the channel being opened was within the accepted size-bounds.

Expected the channel to be opened as before.

Got an error message: 'maxValueInFlight too large: 5000000000 mSAT, max is 500000000 mSAT' 

Tried to make the channel again, but got same error.

Using Eclair 0.2beta9 on Windows 10 build 17763.

> 2019-02-16 22:16:26,421 ERROR f.a.e.channel.Channel  n:0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c c:bc1d7ce5f916a2399d689456f377d9c40290251065175b8adffc12273b965e2a - peer sent error: ascii='maxValueInFlight too large: 5000000000 mSAT, max is 500000000 mSAT' bin=6d617856616c7565496e466c6967687420746f6f206c617267653a2035303030303030303030206d5341542c206d617820697320353030303030303030206d534154
2019-02-16 22:16:26,422 INFO  f.a.eclair.gui.Handlers  - could not open channel java.lang.RuntimeException: peer sent error: 'maxValueInFlight too large: 5000000000 mSAT, max is 500000000 mSAT'

Full log: https://pastebin.com/SxgeQxef

**Comment by sstone** [comment]
5000000000 is indeed larger than 500000000 (there's one extra `0`), so i don't see a problem here ?

Our default setting for `max-htlc-value-in-flight-msat` is 5000000000, you can change it in your own `eclair.conf` (add `eclair.max-htlc-value-in-flight-msat = XXXX`).

Closing because it's not strictly a technical issue, but you can contact us and other eclair users on [gitter](https://gitter.im/ACINQ/eclair).

**Comment by kravens** [comment]
Thanks, I'll try editing the config file. Will start reading on the eclair gitter as well!
