### ISSUE TITLE
GUI shows OFFLINE channels, but a simple connection fixes it.  Can that be automated?

### ISSUE THREAD

**Issue by dscotese** [ACINQ/eclair#876]
When I started trying to fix channels that showed "OFFLINE" by attempts worked **right away**.  It has not yet failed when I find the channel on 1ML and then use the node URI to do a "Simple connection".  It seems that I shouldn't have to be here to make that "simple connection" request just to ensure that routing between my node and the one that is *actually* online but showing offline can proceed.

I expect Eclair to try making a simple connection to all OFFLINE nodes with which I have a channel periodically - every 5 minutes, maybe - just to see if it can solve the problem itself.  It's more a feature request.

So far, every "OFFLINE" channel.

v0.2-beta 9

Windows 10, I don't know the JDK version. How do I find it?

**Comment by viaj3ro** [comment]
I have the same issue. Every day when I check on my node some 5-10 channels have been force closed by my peers in the past 24h due to this issue. another 5-10 are still open but appear to be offline and I have to use @dscotese workaround to get them back online.

That's obviously a major issue. By now I have lost countless well balanced high activity channels and lot's of BTC locked up in force closed channels for days or even weeks.

**Comment by pm47** [comment]
> I expect Eclair to try making a simple connection to all OFFLINE nodes with which I have a channel periodically - every 5 minutes, maybe - just to see if it can solve the problem itself. It's more a feature request.

That is already the case, eclair will attempt to reconnect with an exponential back-off delay, provided that eclair knows the address of the peer. If the peer initiated the connection, then eclair doesn't have its address.

One corner case: eclair initiated the connection but the peer changed its address. In that case you have to manually reconnect, but those peers are not reliable anyway and I highly doubt much traffic would go through them.

> I have the same issue. Every day when I check on my node some 3-6 channels have been force closed by my peers in the past 24h due to this issue.

There is no relationship between disconnections and channels getting closed/force closed. E.g. on a mobile device most of the time the channel is offline, but the channel doestn't get closed.

**Comment by viaj3ro** [comment]
> There is no relationship between disconnections and channels getting closed/force closed. E.g. on a mobile device most of the time the channel is offline, but the channel doestn't get closed.

Yes, there is a very obvious connection between being offline and closed channels. When my node is online, it almost never happens, that channels get closed. The moment it goes offline, people start closing channels that have capacity on their side. That is _active_ channels I opened to them or channels they opened to me. The reason is pretty obvious: routing node operators don't want to have their funds tied up in offline channels. Being offline for 18 hours was enough to lose 50% of my 140 channels. Those 50% accounted for 90% of active channels and 100% of high capacity channels other routing nodes had opened to my node. 

I agree, people shouldn't be so trigger happy when it comes to closing or even force closing channels, but unfortunately they are.

Of course low capacity outgoing channels from non routing mobile nodes won't get closed that quickly.

> One corner case: eclair initiated the connection but the peer changed its address. In that case you have to manually reconnect, but those peers are not reliable anyway and I highly doubt much traffic would go through them.

This morning my two channels to bitrefill, MiltonPusser and a couple more were offline. Just now the channels to Yalls, lnd.lightning.guru and LNBIG.com [lnd-02] were offline. All of them came online again after a manual reconnect.

**Comment by pm47** [comment]
People can close channels when they want and will do it if you node is unreliable, sure. But just being offline won't automatically lead to channels getting closed, which is what I was saying.

Anyway, again automatic reconnection is already in place with the caveats I mentioned in my first answer, so closing this.

**Comment by viaj3ro** [comment]
well, two users report offline channels that stay offline indefinitely until manually reconnected. So I'd argue there is a pretty serious issue here.

I'd assume something with the reconnect routine isn't working properly and it should at least be looked into.

**Comment by dscotese** [comment]
Is there any keyword for which we can search the logs to see the attempts to reconnect to an apparently-offline node?  That would be useful to track down proof one way or the other whether the automatic reconnection is actually being attempted.  There may be a bug in the exponential backoff delay, for example.

**Comment by araspitzu** [comment]
@dscotese you can grep the logs for 'io.Peer' which is the part of eclair handling peer connections, to filter for a specific peer you can additionally grep it's nodeId.

**Comment by pm47** [comment]
Also just `connecting` works
