### ISSUE TITLE
Ignore non Segwit UTXOs

### ISSUE THREAD

**Issue by jpis** [ACINQ/eclair#898]
During launch, Eclair, just stops at any non Segwit UTXOs found with an error reported (see attached screenshot). Instead, it should just ignore any incompatible UTXOs, as long are as at least one is compatible that contains funds.
 

Eclair only uses UTXO it can manage (segwit addresses). It ignores others.

Only one non segwit non -empty  UXTXO prevents Eclair to start with error message (see attached screenshot)

happens every time until I move all the non-Segwit funds to a Segwit adddress

exe file is from 28/10/2018

Windows 10. Eclair connected to bitcoin core 17.1. 

Bitcoin core contains adresses of various format 1, 3, BC.
Look at the attached screenshot

![Eclai launch error](https://user-images.githubusercontent.com/18514601/54354449-f6027a00-4656-11e9-9964-b189e9869728.png)

**Comment by sstone** [comment]
> Eclair only uses UTXO it can manage (segwit addresses). It ignores others.

No it does not, because it does not manage UTXOs at all, and I'm not aware of a way to tell bitcoin core to only select segwit UTXOs when it funds transactions. Not supporting legacy wallets is not much of a limitation imho and we do not plan to change that. If you need to send/receive funds to services that don't support segwit then using a p2sh-segwit wallet should work.

**Comment by jpis** [comment]
"Eclair only uses UTXO it can manage (segwit addresses). It ignores others."
This was my expected behavior, not the current one.

My understanding is that, at launch, Eclair queries bitcoin core the list of receiving adresses. If it finds a non segwit address, it display the error messages and stops. As it is able to detect a non segwit address should'nt it be able to jump to the next address in the list instead?

**Comment by sstone** [comment]
It would not help. Eclair on desktop/server is not a bitcoin wallet and cannot easily filter/select UTXOs. It asks your Bitcoin node to create funding transactions, which will not work if they contain "malleable" outputs. Supporting legacy outputs would require some work, be clumsy and I really don't see the point since you can use p2sh-segwit.
