### ISSUE TITLE
eclair does not start

### ISSUE THREAD

**Issue by seedofpanic** [ACINQ/eclair#903]
Why?
![1](https://user-images.githubusercontent.com/4730204/54597848-5e32d080-4a48-11e9-9848-0bde0a35ee82.jpg)
![2](https://user-images.githubusercontent.com/4730204/54597849-5e32d080-4a48-11e9-9732-ccc994ac6f46.jpg)

**Comment by araspitzu** [comment]
Not a proper bug description

**Comment by seedofpanic** [comment]
Please tell me how to describe the error correctly?

**Comment by araspitzu** [comment]
It's simple, when you open an issue you should follow the template that is being given to you, it looks like:

This issue tracker is only for technical issues related to Eclair.

Please do not open issues for support requests or questions about Lightning or Eclair: use our gitter at https://gitter.im/ACINQ/eclair instead.
Please check that there is not already a similar issue before opening a new one.

Describe the issue 
What behaviour did you expect?

What was the actual behaviour (provide screenshots if the issue is GUI-related)? 

How reliably can you reproduce the issue, what are the steps to do so?

What version of Eclair are you using, where did you get it (website, self-compiled, etc)? 

What environment are you observing the error on (OS, JDK version)? 

 Any extra information that might be useful in the debugging process. 
This is normally the contents of a `eclair.log` or `eclair.conf` file. Raw text or a link to a pastebin type site are preferred.

On top of this is _bon-ton_ to not be too generic with things like "it doesn't work", after all if the issue you open is very generic it will be more work on our side, OTOH if you provide detailed info we'll be able to help you more promptly.
