### ISSUE TITLE
eclair-cli suggestions

### ISSUE THREAD

**Issue by darwin** [ACINQ/eclair#998]
I just integrated eclair into my pet project [Simverse](https://github.com/darwin/simverse). Congratulations, in my (simple) tests eclair has parity with other LN implementations.

I decided to use `eclair-cli` in a similar way how I use `lncli` and `lightning-cli`. Unfortunately I hit a few minor problems, so I wanted to share them here:

1. `eclair-cli` should communicate API errors via shell exit status code. Right now only `curl` failures are reported as non-zero exit status. I would expect also API errors and failed requests to exit with non-zero status code. For example [here](https://github.com/darwin/simverse/blob/7226839822e647929bf370ee8e2fb65f038f008a/toolbox/get_route#L24-L30) my wrapper command `get_route` should exit with zero status code if a route is found and non-zero otherwise. I had to resolve to string matching in eclair case. Please note that other cases for lnd and lightningd can rely on status code of their cli utils.

2. ANSI colors should be optional (and by default respect if the tool is launched in terminal). Please read [this short article](https://eklitzke.org/ansi-color-codes). jq should detect this automatically - but I had a trouble with it - maybe because I go through docker and it allocated a tty for me automagically (even in cases when I wanted to process the output). Anyways you also use ANSI colors in help description and this might need review, so I wanted to mention it.

3. `eval curl` on last line looks fishy. IMO you don't need `eval` and you wanted to use `exec` to replace bash process with the curl process for potentially long-running commands.

**Comment by araspitzu** [comment]
Hi thanks for the report and the suggestions, yes eclair-cli  doesn't leverage a lot the API HTTP response codes and currently only `curl` failures will make it exit with a non-zero status. I'm in favor of having eclair-cli return any non HTTP-200 status code as shell exit status code, this should help you catching most of the problem when invoking it from your script. Also it seems reasonable to have the API return HTTP 404 in case of route not found. Regarding the colors i understand the struggle in parsing text with mixed-in ANSI colors and it's probably a good idea to have them optionally disabled by a command line option. Replacing `eval` with `exec` is fine, mostly because it would help for long running commands (although many APIs are fire-and-foget).

PS. in your example the eclair-cli seems to be invoked with wrong units in the arguments: `--amountMsat="$AMOUNT_SAT"`

**Comment by araspitzu** [comment]
Have you tried invoking the API via curl instead of using the cli as API? I'm asking because on a second thought the cli is designed to be human friendly and not machine readable, so you might just be better off invoking the API directly instead of going through the cli.

**Comment by darwin** [comment]
> ... in your example the eclair-cli seems to be invoked with wrong units

Thanks for catching that bug. 

The point 2 with ANSI colors was resolved on my end. But still it would be nice to have some option to force colors on/off/auto via some env variable (very low priority).

> Have you tried invoking the API via curl instead of using the cli as API?

I considered it but then I decided to go with eclair-cli. Otherwise I would have to write and maintain a similar curl wrapper anyways. Curl-ing directly seemed to be too laborious/verbose. I also provide [generated cli tools](https://github.com/darwin/simverse#-sv-help-aliases) for individual nodes in the cluster for humans and I would want to expose eclair-cli anyways. 

And I don't think human-friendly cli design must be necessary bad for machine. You can detect tty and add ANSI optionally (for humans) and maybe also support something like `--json` or `--data` switch which provides alternative machine-readable output where it makes sense. So we can have/maintain only one cli tool suitable both for humans and machines.

If you were open to some refinements, I could look into eclair-cli and propose some as a PR.

**Comment by araspitzu** [comment]
I actually think that human friendly design is mostly orthogonal to machine-friendly but i hope you can prove me wrong with a PR :), in fact the cli design was meant to be only human readable (that's why colors and json pretty printing), for machine-to-machine communication we provide a full-blown [HTTP API](https://acinq.github.io/eclair/#introduction). I'm in favor of proposed changes 2) and 3) while 1) would require some more discussion.

**Comment by t-bast** [comment]
Closing inactive issue.
Feel free to reopen if necessary.
